// SPDX-License-Identifier: GPL-2.0-or-later
//
// Engine tests.
//
// Part A (runs everywhere, CI included): the apparent-place primitives
// against closed-form magnitudes (20.5" annual aberration, 4.07 mas
// deflection at 90 degrees, 1.75" at the solar limb), and the whole
// engine pipeline on a synthetic SPK kernel with linearly moving bodies,
// where light time, rates and frame composition have exact answers.
//
// Part B (DE440 binary, PROMETHEIA_DE440; SKIP when absent): positions
// against tests/engine_fixtures.inc, generated by
// tools/gen/gen_engine_fixtures.py from the Swiss Ephemeris swetest CLI
// running on the same DE440 file (output-only oracle), so the residuals
// measure the apparent-place and frame models alone. Also: the DE binary
// and de440s.bsp give identical answers through the engine.
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <string>
#include <unistd.h>
#include <vector>

#include <prometheia/apparent.hpp>
#include <prometheia/engine.hpp>
#include <prometheia/frames.hpp>

#include "test_main.hpp"

using namespace prometheia;

namespace {

namespace fs = std::filesystem;

constexpr double kPi = 3.14159265358979323846;
constexpr double kDeg2Rad = kPi / 180.0;
constexpr double kRad2As = 180.0 * 3600.0 / kPi;
constexpr double kAuKm = 149597870.7;
constexpr double kJ2000 = 2451545.0;

double norm3(const double v[3]) {
    return std::sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
}

double angle_as(const double a[3], const double b[3]) {
    const double c[3] = {a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2],
                         a[0] * b[1] - a[1] * b[0]};
    const double d = a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
    return std::atan2(norm3(c), d) * kRad2As;
}

// Great-circle separation of two (lon, lat) pairs in degrees, arcsec.
double sep_as(double lon1, double lat1, double lon2, double lat2) {
    const double a[3] = {std::cos(lat1 * kDeg2Rad) * std::cos(lon1 * kDeg2Rad),
                         std::cos(lat1 * kDeg2Rad) * std::sin(lon1 * kDeg2Rad),
                         std::sin(lat1 * kDeg2Rad)};
    const double b[3] = {std::cos(lat2 * kDeg2Rad) * std::cos(lon2 * kDeg2Rad),
                         std::cos(lat2 * kDeg2Rad) * std::sin(lon2 * kDeg2Rad),
                         std::sin(lat2 * kDeg2Rad)};
    return angle_as(a, b);
}

double wrap180(double d) {
    while (d > 180.0)
        d -= 360.0;
    while (d <= -180.0)
        d += 360.0;
    return d;
}

// ---------------------------------------------------------------------------
// Part A1: primitives.
// ---------------------------------------------------------------------------

TEST(aberration_magnitude_and_direction) {
    // Observer moving at 29.79 km/s perpendicular to the line of sight:
    // the image shifts towards the velocity by asin(v/c) ~ 20.49".
    const double v_kms = 29.79;
    const double v[3] = {0.0, v_kms * 86400.0, 0.0};
    const double p[3] = {5.0, 0.0, 0.0};
    double out[3];
    apparent::aberration(p, v, out);
    const double expect = std::asin(v_kms / 299792.458) * kRad2As;
    CHECK(std::fabs(angle_as(p, out) - expect) < 1e-6);
    CHECK(out[1] > 0.0);                        // towards the velocity
    CHECK(std::fabs(norm3(out) - 5.0) < 1e-12); // length kept
    // Along the velocity: no shift.
    const double q[3] = {0.0, 2.0, 0.0};
    apparent::aberration(q, v, out);
    CHECK(angle_as(q, out) < 1e-9);
    // Aliasing allowed.
    double w[3] = {5.0, 0.0, 0.0};
    apparent::aberration(w, v, w);
    CHECK(std::fabs(angle_as(p, w) - expect) < 1e-6);
}

TEST(light_deflection_magnitudes) {
    // Sun at the origin, observer 1 AU along -x (so sun->observer = -x).
    const double E = kAuKm;
    const double sun_to_obs[3] = {-E, 0.0, 0.0};
    const double eps_limb = 2.0 * apparent::kSunGmOverC2Km / E;

    // Distant star at 90 degrees elongation (+y): 2GM/(c^2 E) = 4.07 mas,
    // pushed away from the Sun.
    const double far = 1e15;
    const double p90[3] = {E, far, 0.0}; // observer->star
    const double q90[3] = {0.0, far, 0.0};
    double out[3];
    apparent::light_deflection(p90, q90, sun_to_obs, apparent::kSunGmOverC2Km, out);
    CHECK(std::fabs(angle_as(p90, out) - eps_limb * kRad2As) < 1e-5);
    CHECK(std::fabs(angle_as(p90, out) * 1000.0 - 4.07) < 0.01);
    CHECK(out[0] / norm3(out) < p90[0] / norm3(p90)); // away from the Sun (+x)

    // Grazing the solar limb (R = 696,000 km): the classical 1.75".
    const double R = 696000.0;
    const double th = std::asin(R / E);
    const double pl[3] = {far * std::cos(th), far * std::sin(th), 0.0};
    const double ql[3] = {pl[0] - E, pl[1], 0.0};
    apparent::light_deflection(pl, ql, sun_to_obs, apparent::kSunGmOverC2Km, out);
    CHECK(std::fabs(angle_as(pl, out) - 1.75) < 0.01);
    CHECK(std::fabs(norm3(out) / norm3(pl) - 1.0) < 1e-12);
}

TEST(frame_bias_matrix_values) {
    double b[9];
    frames::frame_bias_matrix(b);
    // Orthogonal.
    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 3; ++j) {
            double s = 0.0;
            for (int k = 0; k < 3; ++k)
                s += b[3 * i + k] * b[3 * j + k];
            CHECK(std::fabs(s - (i == j ? 1.0 : 0.0)) < 1e-15);
        }
    }
    // The ICRF x axis in the J2000 mean frame: (1, -d_alpha0, xi0) to
    // first order, i.e. y = +14.6 mas, z = -16.617 mas.
    const double mas = 1.0 / (1000.0 * kRad2As);
    CHECK(std::fabs(b[3] - 14.6 * mas) < 0.01 * mas);
    CHECK(std::fabs(b[6] - (-16.617 * mas)) < 0.01 * mas);
    // The ICRF z axis: x = xi0-ish, y = eta0-ish.
    CHECK(std::fabs(b[2] - 16.617 * mas) < 0.01 * mas);
    CHECK(std::fabs(b[5] - 6.8192 * mas) < 0.01 * mas);
}

// ---------------------------------------------------------------------------
// Part A2: synthetic SPK kernel with linear motion.
// ---------------------------------------------------------------------------

constexpr double kDay = 86400.0;

struct LinearBody {
    int id;
    double p[3]; // km at et = 0
    double v[3]; // km/s
};

// Sun, Earth and Jupiter-system barycentre, all wrt the barycentre.
const LinearBody kBodies[] = {
    {10, {1.0e5, -2.0e5, 3.0e4}, {0.01, 0.012, -0.002}},
    {399, {2.6e7, 1.44e8, 6.2e7}, {-29.7, 5.0, 2.2}},
    {5, {7.4e8, 1.2e8, 3.0e7}, {-2.3, 12.3, 5.2}},
};
constexpr double kHalfSpan = 60.0 * 365.25 * kDay; // one record, +/- 60 yr

void linear_state(const LinearBody& b, double et, double out[6]) {
    for (int i = 0; i < 3; ++i) {
        out[i] = b.p[i] + b.v[i] * et;
        out[3 + i] = b.v[i] * kDay;
    }
}

struct Writer {
    std::string out;
    void f64(double v) { out.append(reinterpret_cast<const char*>(&v), 8); }
    void i32(int32_t v) { out.append(reinterpret_cast<const char*>(&v), 4); }
    void text(std::string s, size_t n) {
        s.resize(n, ' ');
        out += s;
    }
    void pad_to(size_t n) { out.resize(n, '\0'); }
};

std::string write_linear_spk(const fs::path& path) {
    constexpr int kFirstWord = 3 * 1024 / 8 + 1;
    Writer data;
    std::vector<std::pair<int, int>> addr;
    for (const LinearBody& b : kBodies) {
        const int begin = kFirstWord + int(data.out.size() / 8);
        // One type-3 record, degree 1: x(tau) = c0 + c1 tau, tau = et / R.
        data.f64(0.0);       // MID
        data.f64(kHalfSpan); // RADIUS
        for (int c = 0; c < 3; ++c) {
            data.f64(b.p[c]);
            data.f64(b.v[c] * kHalfSpan);
        }
        for (int c = 0; c < 3; ++c) {
            data.f64(b.v[c]);
            data.f64(0.0);
        }
        data.f64(-kHalfSpan);      // INIT
        data.f64(2.0 * kHalfSpan); // INTLEN
        data.f64(2.0 + 6 * 2);     // RSIZE
        data.f64(1.0);             // N
        addr.push_back({begin, kFirstWord + int(data.out.size() / 8) - 1});
    }
    Writer f;
    f.text("DAF/SPK ", 8);
    f.i32(2);
    f.i32(6);
    f.text("SYNTHETIC LINEAR", 60);
    f.i32(2);
    f.i32(2);
    f.i32(kFirstWord + int(data.out.size() / 8));
    f.text("LTL-IEEE", 8);
    f.pad_to(699);
    const char ftp[] = "FTPSTR:\r:\n:\r\n:\r\0:\x81:\x10\xce:ENDFTP";
    f.out.append(ftp, sizeof(ftp) - 1);
    f.pad_to(1024);
    // Summary record.
    f.f64(0.0);
    f.f64(0.0);
    f.f64(double(std::size(kBodies)));
    for (size_t i = 0; i < std::size(kBodies); ++i) {
        f.f64(-kHalfSpan);
        f.f64(kHalfSpan);
        f.i32(kBodies[i].id);
        f.i32(0);
        f.i32(1);
        f.i32(3);
        f.i32(addr[i].first);
        f.i32(addr[i].second);
    }
    f.pad_to(2048);
    for (const LinearBody& b : kBodies)
        f.text("BODY " + std::to_string(b.id), 40);
    f.pad_to(3072);
    f.out += data.out;
    f.pad_to((f.out.size() + 1023) / 1024 * 1024);
    FILE* fp = std::fopen(path.c_str(), "wb");
    std::fwrite(f.out.data(), 1, f.out.size(), fp);
    std::fclose(fp);
    return path.string();
}

struct TempFile {
    fs::path path;
    explicit TempFile(const char* stem) {
        path = fs::temp_directory_path() /
               (std::string("prometheia-") + stem + "-" + std::to_string(::getpid()) + ".bsp");
    }
    ~TempFile() { fs::remove(path); }
};

Engine open_synthetic(const TempFile& tf) {
    write_linear_spk(tf.path);
    auto e = Engine::open(tf.path.string());
    CHECK(e.ok());
    if (!e)
        std::printf("  open: %s\n", e.error().message.c_str());
    return std::move(e).value();
}

double et_of_tdb(double jd_tdb) {
    return (jd_tdb - kJ2000) * kDay;
}

TEST(engine_synthetic_geometric) {
    TempFile tf("engine-geo");
    Engine e = open_synthetic(tf);
    CalcOptions o = CalcOptions::geometric();
    o.frame = Frame::ICRF;
    o.coords = Coords::Equatorial;
    const double jd_tt = 2460000.5;
    auto r = e.calc(body::kJupiter, jd_tt, o);
    CHECK(r.ok());
    const double et = et_of_tdb(time::tdb_from_tt(jd_tt));
    double j[6], g[6];
    linear_state(kBodies[2], et, j);
    linear_state(kBodies[1], et, g);
    const Position& p = r.value().pos;
    for (int i = 0; i < 3; ++i) {
        // Chebyshev coefficients of ~5e10 km round at the 1e-5 km level.
        CHECK(std::fabs(p.xyz_au[i] * kAuKm - (j[i] - g[i])) < 1e-3);
        // Linear motion: the central difference is exact up to rounding.
        CHECK(std::fabs(p.vel_au_day[i] * kAuKm - (j[3 + i] - g[3 + i])) < 0.1);
    }
    // Spherical form consistent with the vector.
    CHECK(std::fabs(p.dist_au - norm3(p.xyz_au)) < 1e-15);
    const double lon = std::atan2(p.xyz_au[1], p.xyz_au[0]) / kDeg2Rad;
    CHECK(std::fabs(wrap180(p.lon_deg - lon)) < 1e-12);
    CHECK(r.value().provenance.light_time_days == 0.0);
    CHECK(!r.value().sigma_arcsec.has_value());
    CHECK(r.value().provenance.source.find("SPK") != std::string_view::npos);
}

TEST(engine_synthetic_light_time) {
    TempFile tf("engine-lt");
    Engine e = open_synthetic(tf);
    CalcOptions o = CalcOptions::astrometric();
    o.frame = Frame::ICRF;
    o.coords = Coords::Equatorial;
    const double jd_tt = 2451545.0 + 1234.5678;
    auto r = e.calc(body::kJupiter, jd_tt, o);
    CHECK(r.ok());
    const double tau = r.value().provenance.light_time_days;
    const double et = et_of_tdb(time::tdb_from_tt(jd_tt));
    double j[6], g[6];
    linear_state(kBodies[2], et - tau * kDay, j);
    linear_state(kBodies[1], et, g);
    const double d[3] = {j[0] - g[0], j[1] - g[1], j[2] - g[2]};
    // The light-time equation holds: |x_J(t - tau) - x_E(t)| = c tau.
    CHECK(std::fabs(norm3(d) - tau * apparent::kLightKmPerDay) < 1e-3);
    const Position& p = r.value().pos;
    for (int i = 0; i < 3; ++i)
        CHECK(std::fabs(p.xyz_au[i] * kAuKm - d[i]) < 1e-3);
    CHECK(tau > 0.01 && tau < 0.2); // a few AU
}

TEST(engine_synthetic_corrections_compose) {
    TempFile tf("engine-app");
    Engine e = open_synthetic(tf);
    const double jd_tt = 2461300.25;
    CalcOptions astro = CalcOptions::astrometric();
    astro.frame = Frame::ICRF;
    astro.coords = Coords::Equatorial;
    CalcOptions app = CalcOptions::apparent();
    app.frame = Frame::ICRF;
    app.coords = Coords::Equatorial;
    auto ra = e.calc(body::kJupiter, jd_tt, astro);
    auto rp = e.calc(body::kJupiter, jd_tt, app);
    CHECK(ra.ok() && rp.ok());

    // Rebuild the apparent vector from the astrometric one.
    const double tau = ra.value().provenance.light_time_days;
    const double et = et_of_tdb(time::tdb_from_tt(jd_tt));
    double j[6], g[6], s[6];
    linear_state(kBodies[2], et - tau * kDay, j);
    linear_state(kBodies[1], et, g);
    linear_state(kBodies[0], et, s);
    double p[3];
    for (int i = 0; i < 3; ++i)
        p[i] = ra.value().pos.xyz_au[i] * kAuKm;
    const double sb[3] = {j[0] - s[0], j[1] - s[1], j[2] - s[2]};
    const double so[3] = {g[0] - s[0], g[1] - s[1], g[2] - s[2]};
    apparent::light_deflection(p, sb, so, apparent::kSunGmOverC2Km, p);
    apparent::aberration(p, g + 3, p);
    double q[3];
    for (int i = 0; i < 3; ++i)
        q[i] = rp.value().pos.xyz_au[i] * kAuKm;
    CHECK(angle_as(p, q) < 1e-7);
    // And the correction is annual-aberration sized.
    double a[3];
    for (int i = 0; i < 3; ++i)
        a[i] = ra.value().pos.xyz_au[i];
    const double shift = angle_as(a, rp.value().pos.xyz_au);
    CHECK(shift > 1.0 && shift < 21.0);
}

TEST(engine_synthetic_frames_compose) {
    TempFile tf("engine-frames");
    Engine e = open_synthetic(tf);
    const double jd_tt = 2470000.5; // inside the kernel's +/- 60 yr
    CalcOptions o = CalcOptions::geometric();
    o.speed = false;
    // Every query must succeed: a failed Result carries a zero Position,
    // which would make the comparisons below vacuous.
    auto calc = [&](const CalcOptions& opts) {
        auto r = e.calc(body::kJupiter, jd_tt, opts);
        CHECK(r.ok());
        return r.ok() ? r.value().pos : Position{};
    };

    o.frame = Frame::ICRF;
    o.coords = Coords::Equatorial;
    const Position icrf = calc(o);

    // J2000 equatorial = B * ICRF.
    double b[9];
    frames::frame_bias_matrix(b);
    o.frame = Frame::J2000;
    const Position j2k = calc(o);
    for (int i = 0; i < 3; ++i) {
        const double x = b[3 * i] * icrf.xyz_au[0] + b[3 * i + 1] * icrf.xyz_au[1] +
                         b[3 * i + 2] * icrf.xyz_au[2];
        CHECK(std::fabs(x - j2k.xyz_au[i]) < 1e-12);
    }

    // True minus mean ecliptic longitude of date = dpsi; latitude equal.
    o.coords = Coords::Ecliptic;
    o.frame = Frame::MeanOfDate;
    const Position mean = calc(o);
    o.frame = Frame::TrueOfDate;
    const Position tru = calc(o);
    double dpsi, deps;
    frames::nutation(jd_tt, dpsi, deps);
    CHECK(std::fabs(wrap180(tru.lon_deg - mean.lon_deg) * kDeg2Rad - dpsi) < 1e-12);
    CHECK(std::fabs(tru.lat_deg - mean.lat_deg) < 1e-12);

    // Equatorial of date: RA/Dec agree with rotating the true ecliptic
    // vector back by the true obliquity.
    o.coords = Coords::Equatorial;
    const Position eq = calc(o);
    const double eps = frames::mean_obliquity(jd_tt) + deps;
    const double c = std::cos(eps), s = std::sin(eps);
    const double y = c * tru.xyz_au[1] - s * tru.xyz_au[2];
    const double z = s * tru.xyz_au[1] + c * tru.xyz_au[2];
    CHECK(std::fabs(tru.xyz_au[0] - eq.xyz_au[0]) < 1e-13);
    CHECK(std::fabs(y - eq.xyz_au[1]) < 1e-13);
    CHECK(std::fabs(z - eq.xyz_au[2]) < 1e-13);
}

TEST(engine_synthetic_centers_and_errors) {
    TempFile tf("engine-err");
    Engine e = open_synthetic(tf);
    const double jd_tt = 2451545.0;
    CalcOptions o = CalcOptions::geometric();
    o.frame = Frame::ICRF;
    o.coords = Coords::Equatorial;

    // Heliocentric Earth = Earth - Sun; barycentric Sun = Sun.
    o.center = Center::Heliocentric;
    auto h = e.calc(body::kEarth, jd_tt, o);
    CHECK(h.ok());
    const double et = et_of_tdb(time::tdb_from_tt(jd_tt));
    double g[6], s[6];
    linear_state(kBodies[1], et, g);
    linear_state(kBodies[0], et, s);
    for (int i = 0; i < 3; ++i)
        CHECK(std::fabs(h.value().pos.xyz_au[i] * kAuKm - (g[i] - s[i])) < 1e-6);
    o.center = Center::Barycentric;
    auto sb = e.calc(body::kSun, jd_tt, o);
    CHECK(sb.ok());
    for (int i = 0; i < 3; ++i)
        CHECK(std::fabs(sb.value().pos.xyz_au[i] * kAuKm - s[i]) < 1e-9);

    // Topocentric: the observer sits within an Earth radius of the geocentre.
    CalcOptions t = o;
    t.center = Center::Topocentric;
    t.site = {8.55 * kDeg2Rad, 47.37 * kDeg2Rad, 500.0};
    o.center = Center::Geocentric;
    auto rg = e.calc(body::kJupiter, jd_tt, o);
    auto rt = e.calc(body::kJupiter, jd_tt, t);
    CHECK(rg.ok() && rt.ok());
    const Position geo = rg.ok() ? rg.value().pos : Position{};
    const Position top = rt.ok() ? rt.value().pos : Position{};
    double dd[3];
    for (int i = 0; i < 3; ++i)
        dd[i] = (geo.xyz_au[i] - top.xyz_au[i]) * kAuKm;
    CHECK(norm3(dd) > 6350.0 && norm3(dd) < 6380.0);

    // Errors.
    o.center = Center::Geocentric;
    CHECK(e.calc(body::kEarth, jd_tt, o).error().code == ErrorCode::ArgumentError);
    o.center = Center::Heliocentric;
    CHECK(e.calc(body::kSun, jd_tt, o).error().code == ErrorCode::ArgumentError);
    o.center = Center::Barycentric;
    CHECK(e.calc(body::kSolarSystemBary, jd_tt, o).error().code == ErrorCode::ArgumentError);
    o.center = Center::Geocentric;
    CHECK(e.calc(body::kMars, jd_tt, o).error().code == ErrorCode::NotFound);
    CHECK(e.calc(body::kJupiter, NAN, o).error().code == ErrorCode::ArgumentError);
    CHECK(!e.calc(body::kJupiter, jd_tt + 100.0 * 365.25, o).ok()); // outside coverage

    Engine closed;
    CHECK(closed.calc(body::kSun, jd_tt).error().code == ErrorCode::ArgumentError);
    CHECK(Engine::open("/nonexistent/prometheia.bsp").error().code == ErrorCode::IoError);
    const fs::path junk =
        fs::temp_directory_path() / ("prometheia-junk-" + std::to_string(::getpid()) + ".bin");
    {
        FILE* fp = std::fopen(junk.c_str(), "wb");
        std::fputs("definitely not an ephemeris", fp);
        std::fclose(fp);
    }
    CHECK(!Engine::open(junk.string()).ok());
    fs::remove(junk);
}

TEST(engine_calc_ut_uses_delta_t) {
    TempFile tf("engine-ut");
    Engine e = open_synthetic(tf);
    struct Fixed final : time::DeltaTModel {
        double delta_t_seconds(double) const override { return 100.0; }
    } fixed;
    e.set_delta_t_model(&fixed);
    CalcOptions o = CalcOptions::geometric();
    const double jd_ut = 2455000.5;
    auto a = e.calc_ut(body::kJupiter, jd_ut, o);
    auto b = e.calc(body::kJupiter, jd_ut + 100.0 / 86400.0, o);
    CHECK(a.ok() && b.ok());
    CHECK(a.ok() && b.ok() && a.value().pos.lon_deg == b.value().pos.lon_deg);
    e.set_delta_t_model(nullptr); // default model again
    auto c = e.calc_ut(body::kJupiter, jd_ut, o);
    CHECK(c.ok() && c.value().pos.lon_deg != a.value().pos.lon_deg);
}

// ---------------------------------------------------------------------------
// Part B: DE440 against the swetest fixtures.
// ---------------------------------------------------------------------------

enum class Mode {
    Apparent,
    ApparentEquatorial,
    ApparentJ2000,
    GeometricJ2000,
    BarycentricJ2000,
    HeliocentricJ2000,
    Topocentric,
};

#include "engine_fixtures.inc"

std::string env_or(const char* var, const std::string& fallback) {
    const char* env = std::getenv(var);
    return env && *env ? std::string(env) : fallback;
}

bool available(const std::string& path, const char* var) {
    if (fs::exists(path))
        return true;
    std::printf("  [SKIP] '%s' not found (set %s to enable)\n", path.c_str(), var);
    return false;
}

const std::string kDe440Path =
    env_or("PROMETHEIA_DE440", std::string(PROMETHEIA_SOURCE_DIR) + "/ephe/linux_p1550p2650.440");
const std::string kDe440sPath =
    env_or("PROMETHEIA_DE440S", std::string(PROMETHEIA_SOURCE_DIR) + "/ephe/de440s.bsp");

struct FixedDeltaT final : time::DeltaTModel {
    double seconds = 0.0;
    double delta_t_seconds(double) const override { return seconds; }
};

CalcOptions options_for(Mode m) {
    CalcOptions o;
    switch (m) {
    case Mode::Apparent:
        break;
    case Mode::ApparentEquatorial:
        o.coords = Coords::Equatorial;
        break;
    case Mode::ApparentJ2000:
        o.frame = Frame::J2000;
        break;
    case Mode::GeometricJ2000:
        o = CalcOptions::geometric();
        o.frame = Frame::J2000;
        break;
    case Mode::BarycentricJ2000:
        o = CalcOptions::geometric();
        o.frame = Frame::J2000;
        o.center = Center::Barycentric;
        break;
    case Mode::HeliocentricJ2000:
        o = CalcOptions::geometric();
        o.frame = Frame::J2000;
        o.center = Center::Heliocentric;
        break;
    case Mode::Topocentric:
        o.center = Center::Topocentric;
        o.site = {8.55 * kDeg2Rad, 47.37 * kDeg2Rad, 500.0};
        break;
    }
    o.speed = false;
    return o;
}

const char* mode_name(Mode m) {
    static const char* names[] = {"apparent (true ecliptic of date)",
                                  "apparent (true equator of date)",
                                  "apparent (J2000 ecliptic)",
                                  "geometric (J2000 ecliptic)",
                                  "barycentric geometric (J2000)",
                                  "heliocentric geometric (J2000)",
                                  "topocentric apparent"};
    return names[int(m)];
}

TEST(de440_engine_matches_swetest) {
    if (!available(kDe440Path, "PROMETHEIA_DE440"))
        return;
    auto opened = Engine::open(kDe440Path);
    CHECK(opened.ok());
    if (!opened)
        return;
    Engine e = std::move(opened).value();
    CHECK(e.source() == "JPL DE440 binary");
    FixedDeltaT dt;
    e.set_delta_t_model(&dt);

    struct Worst {
        double planets_as = 0.0, moon_as = 0.0, dist_au = 0.0, moon_dist_au = 0.0;
    };
    Worst worst[7];
    for (const Fixture& f : kFixtures) {
        for (const DeltaTFixture& d : kSweDeltaT)
            if (d.jd_tt == f.jd_tt)
                dt.seconds = d.seconds;
        auto r = e.calc(f.body, f.jd_tt, options_for(f.mode));
        CHECK(r.ok());
        if (!r) {
            std::printf("  body %d: %s\n", f.body, r.error().message.c_str());
            continue;
        }
        const Position& p = r.value().pos;
        const double sep = sep_as(p.lon_deg, p.lat_deg, f.a, f.b);
        const double dr = std::fabs(p.dist_au - f.r);
        Worst& w = worst[int(f.mode)];
        if (f.body == body::kMoon) {
            w.moon_as = std::max(w.moon_as, sep);
            w.moon_dist_au = std::max(w.moon_dist_au, dr);
        } else {
            w.planets_as = std::max(w.planets_as, sep);
            w.dist_au = std::max(w.dist_au, dr);
        }
    }
    for (int m = 0; m < 7; ++m) {
        const Worst& w = worst[m];
        std::printf("  %-34s Sun/planets %.4f\"  Moon %.4f\"  |dr| %.1e / %.1e AU\n",
                    mode_name(Mode(m)), w.planets_as, w.moon_as, w.dist_au, w.moon_dist_au);
        const bool date_frame = Mode(m) == Mode::Apparent || Mode(m) == Mode::ApparentEquatorial ||
                                Mode(m) == Mode::Topocentric;
        // J2000-frame modes isolate the correction pipeline: SWE prints
        // 0.0001" and the Moon carries ~1 mas of unexplained difference.
        // Date frames add SWE's non-IAU-2006 long-term precession (~2 mas
        // over 1800-2100). SWE rotates the topocentric site with the mean
        // pole, ~0.1" at the Moon (docs/ENGINE.md).
        CHECK(w.planets_as < (date_frame ? 0.005 : 0.0005));
        CHECK(w.moon_as < (Mode(m) == Mode::Topocentric ? 0.25 : (date_frame ? 0.005 : 0.003)));
        CHECK(w.dist_au < 2e-9);
        CHECK(w.moon_dist_au < (Mode(m) == Mode::Topocentric ? 5e-9 : 2e-9));
    }
}

TEST(de440_engine_rates_match_differenced_swetest) {
    if (!available(kDe440Path, "PROMETHEIA_DE440"))
        return;
    auto opened = Engine::open(kDe440Path);
    if (!opened)
        return;
    Engine e = std::move(opened).value();
    double worst_lon = 0.0, worst_lat = 0.0, worst_dist = 0.0;
    for (const SpeedFixture& f : kSpeedFixtures) {
        auto r = e.calc(f.body, f.jd_tt);
        CHECK(r.ok());
        if (!r)
            continue;
        const Position& p = r.value().pos;
        const double dlon = wrap180(f.a1 - f.a0) / (2.0 * kSpeedH);
        const double dlat = (f.b1 - f.b0) / (2.0 * kSpeedH);
        const double ddist = (f.r1 - f.r0) / (2.0 * kSpeedH);
        worst_lon = std::max(worst_lon, std::fabs(p.lon_speed - dlon));
        worst_lat = std::max(worst_lat, std::fabs(p.lat_speed - dlat));
        worst_dist = std::max(worst_dist, std::fabs(p.dist_speed - ddist));
    }
    std::printf("  rate residuals: lon %.1e deg/day, lat %.1e deg/day, dist %.1e AU/day\n",
                worst_lon, worst_lat, worst_dist);
    // Differenced 0.0001" fixtures over 0.02 day resolve ~1.4e-6 deg/day.
    CHECK(worst_lon < 5e-6);
    CHECK(worst_lat < 5e-6);
    CHECK(worst_dist < 1e-7);
}

TEST(de440_binary_and_spk_agree_through_engine) {
    if (!available(kDe440Path, "PROMETHEIA_DE440") || !available(kDe440sPath, "PROMETHEIA_DE440S"))
        return;
    auto a = Engine::open(kDe440Path);
    auto b = Engine::open(kDe440sPath);
    CHECK(a.ok() && b.ok());
    if (!a || !b)
        return;
    Engine ea = std::move(a).value();
    Engine eb = std::move(b).value();
    CHECK(eb.source().find("SPK") != std::string_view::npos);
    const int ids[] = {10, 301, 199, 299, 4, 5, 6, 7, 8, 9};
    double worst = 0.0;
    for (double jd = 2400000.5; jd < 2500000.0; jd += 3652.5 + 0.37) {
        for (int id : ids) {
            auto ra = ea.calc(id, jd);
            auto rb = eb.calc(id, jd);
            CHECK(ra.ok() && rb.ok());
            if (!ra || !rb)
                continue;
            const Position& p = ra.value().pos;
            const Position& q = rb.value().pos;
            worst = std::max(worst, sep_as(p.lon_deg, p.lat_deg, q.lon_deg, q.lat_deg));
        }
    }
    std::printf("  DE440 binary vs de440s.bsp through the engine: %.1e\"\n", worst);
    // The containers agree to ~4 cm (docs/SPK.md): 2e-5" at the Moon.
    CHECK(worst < 5e-5);
}

} // namespace

int main() {
    return ptest::run_all();
}
