// SPDX-License-Identifier: GPL-2.0-or-later
//
// Engine tests.
//
// Part A (runs everywhere, no data files needed): the apparent-place primitives
// against closed-form magnitudes (20.5" annual aberration, 4.07 mas
// deflection at 90 degrees, 1.75" at the solar limb), and the whole
// engine pipeline on a synthetic SPK kernel with linearly moving bodies,
// where light time, rates and frame composition have exact answers.
//
// Part B (DE440 binary, PROMETHEIA_DE440; SKIP when absent): positions
// against tests/engine_fixtures.inc, generated by
// tools/gen/gen_engine_fixtures.py from the Swiss Ephemeris swetest CLI
// running on the same DE440 file (output-only oracle), so the residuals
// measure the apparent-place and frame models alone. Also: the DE binary
// and de440s.bsp give identical answers through the engine.
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <string>
#include <unistd.h>
#include <vector>

#include <prometheia/apparent.hpp>
#include <prometheia/de.hpp>
#include <prometheia/engine.hpp>
#include <prometheia/forces.hpp>
#include <prometheia/frames.hpp>
#include <prometheia/stars.hpp>

#include "synthetic_spk.hpp"
#include <doctest/doctest.h>

using synth::et_of_tdb;
using synth::kBodies;
using synth::kDay;
using synth::linear_state;
using synth::open_synthetic;
using synth::TempFile;

using namespace prometheia;

namespace {

namespace fs = std::filesystem;

constexpr double kPi = 3.14159265358979323846;
constexpr double kDeg2Rad = kPi / 180.0;
constexpr double kRad2As = 180.0 * 3600.0 / kPi;
constexpr double kAuKm = 149597870.7;
constexpr double kJ2000 = 2451545.0;

double norm3(const double v[3]) {
    return std::sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
}

double angle_as(const double a[3], const double b[3]) {
    const double c[3] = {a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2],
                         a[0] * b[1] - a[1] * b[0]};
    const double d = a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
    return std::atan2(norm3(c), d) * kRad2As;
}

// Great-circle separation of two (lon, lat) pairs in degrees, arcsec.
double sep_as(double lon1, double lat1, double lon2, double lat2) {
    const double a[3] = {std::cos(lat1 * kDeg2Rad) * std::cos(lon1 * kDeg2Rad),
                         std::cos(lat1 * kDeg2Rad) * std::sin(lon1 * kDeg2Rad),
                         std::sin(lat1 * kDeg2Rad)};
    const double b[3] = {std::cos(lat2 * kDeg2Rad) * std::cos(lon2 * kDeg2Rad),
                         std::cos(lat2 * kDeg2Rad) * std::sin(lon2 * kDeg2Rad),
                         std::sin(lat2 * kDeg2Rad)};
    return angle_as(a, b);
}

double wrap180(double d) {
    while (d > 180.0)
        d -= 360.0;
    while (d <= -180.0)
        d += 360.0;
    return d;
}

double wrap360(double d) {
    while (d < 0.0)
        d += 360.0;
    while (d >= 360.0)
        d -= 360.0;
    return d;
}

// ---------------------------------------------------------------------------
// Part A1: primitives.
// ---------------------------------------------------------------------------

TEST_CASE("aberration_magnitude_and_direction") {
    // Observer moving at 29.79 km/s perpendicular to the line of sight:
    // the image shifts towards the velocity by asin(v/c) ~ 20.49".
    const double v_kms = 29.79;
    const double v[3] = {0.0, v_kms * 86400.0, 0.0};
    const double p[3] = {5.0, 0.0, 0.0};
    double out[3];
    apparent::aberration(p, v, out);
    const double expect = std::asin(v_kms / 299792.458) * kRad2As;
    CHECK(std::fabs(angle_as(p, out) - expect) < 1e-6);
    CHECK(out[1] > 0.0);                        // towards the velocity
    CHECK(std::fabs(norm3(out) - 5.0) < 1e-12); // length kept
    // Along the velocity: no shift.
    const double q[3] = {0.0, 2.0, 0.0};
    apparent::aberration(q, v, out);
    CHECK(angle_as(q, out) < 1e-9);
    // Aliasing allowed.
    double w[3] = {5.0, 0.0, 0.0};
    apparent::aberration(w, v, w);
    CHECK(std::fabs(angle_as(p, w) - expect) < 1e-6);
}

TEST_CASE("light_deflection_magnitudes") {
    // Sun at the origin, observer 1 AU along -x (so sun->observer = -x).
    const double E = kAuKm;
    const double sun_to_obs[3] = {-E, 0.0, 0.0};
    const double eps_limb = 2.0 * apparent::kSunGmOverC2Km / E;

    // Distant star at 90 degrees elongation (+y): 2GM/(c^2 E) = 4.07 mas,
    // pushed away from the Sun.
    const double far = 1e15;
    const double p90[3] = {E, far, 0.0}; // observer->star
    const double q90[3] = {0.0, far, 0.0};
    double out[3];
    apparent::light_deflection(p90, q90, sun_to_obs, apparent::kSunGmOverC2Km, out);
    CHECK(std::fabs(angle_as(p90, out) - eps_limb * kRad2As) < 1e-5);
    CHECK(std::fabs(angle_as(p90, out) * 1000.0 - 4.07) < 0.01);
    CHECK(out[0] / norm3(out) < p90[0] / norm3(p90)); // away from the Sun (+x)

    // Grazing the solar limb (R = 696,000 km): the classical 1.75".
    const double R = 696000.0;
    const double th = std::asin(R / E);
    const double pl[3] = {far * std::cos(th), far * std::sin(th), 0.0};
    const double ql[3] = {pl[0] - E, pl[1], 0.0};
    apparent::light_deflection(pl, ql, sun_to_obs, apparent::kSunGmOverC2Km, out);
    CHECK(std::fabs(angle_as(pl, out) - 1.75) < 0.01);
    CHECK(std::fabs(norm3(out) / norm3(pl) - 1.0) < 1e-12);
}

TEST_CASE("frame_bias_matrix_values") {
    double b[9];
    frames::frame_bias_matrix(b);
    // Orthogonal.
    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 3; ++j) {
            double s = 0.0;
            for (int k = 0; k < 3; ++k)
                s += b[3 * i + k] * b[3 * j + k];
            CHECK(std::fabs(s - (i == j ? 1.0 : 0.0)) < 1e-15);
        }
    }
    // The ICRF x axis in the J2000 mean frame: (1, -d_alpha0, xi0) to
    // first order, i.e. y = +14.6 mas, z = -16.617 mas.
    const double mas = 1.0 / (1000.0 * kRad2As);
    CHECK(std::fabs(b[3] - 14.6 * mas) < 0.01 * mas);
    CHECK(std::fabs(b[6] - (-16.617 * mas)) < 0.01 * mas);
    // The ICRF z axis: x = xi0-ish, y = eta0-ish.
    CHECK(std::fabs(b[2] - 16.617 * mas) < 0.01 * mas);
    CHECK(std::fabs(b[5] - 6.8192 * mas) < 0.01 * mas);
}

// The synthetic kernel moved to synthetic_spk.hpp.
double et_of_tdb(double jd_tdb) {
    return (jd_tdb - kJ2000) * kDay;
}

TEST_CASE("engine_synthetic_geometric") {
    TempFile tf("engine-geo");
    Engine e = open_synthetic(tf);
    CalcOptions o = CalcOptions::geometric();
    o.frame = Frame::ICRF;
    o.coords = Coords::Equatorial;
    const double jd_tt = 2460000.5;
    auto r = e.calc(body::kJupiter, jd_tt, o);
    CHECK(r.ok());
    const double et = et_of_tdb(time::tdb_from_tt(jd_tt));
    double j[6], g[6];
    linear_state(kBodies[2], et, j);
    linear_state(kBodies[1], et, g);
    const Position& p = r.value().pos;
    for (int i = 0; i < 3; ++i) {
        // Chebyshev coefficients of ~5e10 km round at the 1e-5 km level.
        CHECK(std::fabs(p.xyz_au[i] * kAuKm - (j[i] - g[i])) < 1e-3);
        // Linear motion: the central difference is exact up to rounding.
        CHECK(std::fabs(p.vel_au_day[i] * kAuKm - (j[3 + i] - g[3 + i])) < 0.1);
    }
    // Spherical form consistent with the vector.
    CHECK(std::fabs(p.dist_au - norm3(p.xyz_au)) < 1e-15);
    const double lon = std::atan2(p.xyz_au[1], p.xyz_au[0]) / kDeg2Rad;
    CHECK(std::fabs(wrap180(p.lon_deg - lon)) < 1e-12);
    CHECK(r.value().provenance.light_time_days == 0.0);
    CHECK(!r.value().sigma_arcsec.has_value());
    CHECK(r.value().provenance.source.find("SPK") != std::string_view::npos);
}

TEST_CASE("engine_synthetic_light_time") {
    TempFile tf("engine-lt");
    Engine e = open_synthetic(tf);
    CalcOptions o = CalcOptions::astrometric();
    o.frame = Frame::ICRF;
    o.coords = Coords::Equatorial;
    const double jd_tt = 2451545.0 + 1234.5678;
    auto r = e.calc(body::kJupiter, jd_tt, o);
    CHECK(r.ok());
    const double tau = r.value().provenance.light_time_days;
    const double et = et_of_tdb(time::tdb_from_tt(jd_tt));
    double j[6], g[6];
    linear_state(kBodies[2], et - tau * kDay, j);
    linear_state(kBodies[1], et, g);
    const double d[3] = {j[0] - g[0], j[1] - g[1], j[2] - g[2]};
    // The light-time equation holds: |x_J(t - tau) - x_E(t)| = c tau.
    CHECK(std::fabs(norm3(d) - tau * apparent::kLightKmPerDay) < 1e-3);
    const Position& p = r.value().pos;
    for (int i = 0; i < 3; ++i)
        CHECK(std::fabs(p.xyz_au[i] * kAuKm - d[i]) < 1e-3);
    CHECK(tau > 0.01);
    CHECK(tau < 0.2); // a few AU
}

TEST_CASE("engine_synthetic_corrections_compose") {
    TempFile tf("engine-app");
    Engine e = open_synthetic(tf);
    const double jd_tt = 2461300.25;
    CalcOptions astro = CalcOptions::astrometric();
    astro.frame = Frame::ICRF;
    astro.coords = Coords::Equatorial;
    CalcOptions app = CalcOptions::apparent();
    app.frame = Frame::ICRF;
    app.coords = Coords::Equatorial;
    auto ra = e.calc(body::kJupiter, jd_tt, astro);
    auto rp = e.calc(body::kJupiter, jd_tt, app);
    CHECK(ra.ok());
    CHECK(rp.ok());

    // Rebuild the apparent vector from the astrometric one.
    const double tau = ra.value().provenance.light_time_days;
    const double et = et_of_tdb(time::tdb_from_tt(jd_tt));
    double j[6], g[6], s[6];
    linear_state(kBodies[2], et - tau * kDay, j);
    linear_state(kBodies[1], et, g);
    linear_state(kBodies[0], et, s);
    double p[3];
    for (int i = 0; i < 3; ++i)
        p[i] = ra.value().pos.xyz_au[i] * kAuKm;
    const double sb[3] = {j[0] - s[0], j[1] - s[1], j[2] - s[2]};
    const double so[3] = {g[0] - s[0], g[1] - s[1], g[2] - s[2]};
    apparent::light_deflection(p, sb, so, apparent::kSunGmOverC2Km, p);
    apparent::aberration(p, g + 3, p);
    double q[3];
    for (int i = 0; i < 3; ++i)
        q[i] = rp.value().pos.xyz_au[i] * kAuKm;
    CHECK(angle_as(p, q) < 1e-7);
    // And the correction is annual-aberration sized.
    double a[3];
    for (int i = 0; i < 3; ++i)
        a[i] = ra.value().pos.xyz_au[i];
    const double shift = angle_as(a, rp.value().pos.xyz_au);
    CHECK(shift > 1.0);
    CHECK(shift < 21.0);
}

TEST_CASE("engine_synthetic_frames_compose") {
    TempFile tf("engine-frames");
    Engine e = open_synthetic(tf);
    const double jd_tt = 2470000.5; // inside the kernel's +/- 60 yr
    CalcOptions o = CalcOptions::geometric();
    o.speed = false;
    // Every query must succeed: a failed Result carries a zero Position,
    // which would make the comparisons below vacuous.
    auto calc = [&](const CalcOptions& opts) {
        auto r = e.calc(body::kJupiter, jd_tt, opts);
        CHECK(r.ok());
        return r.ok() ? r.value().pos : Position{};
    };

    o.frame = Frame::ICRF;
    o.coords = Coords::Equatorial;
    const Position icrf = calc(o);

    // J2000 equatorial = B * ICRF.
    double b[9];
    frames::frame_bias_matrix(b);
    o.frame = Frame::J2000;
    const Position j2k = calc(o);
    for (int i = 0; i < 3; ++i) {
        const double x = b[3 * i] * icrf.xyz_au[0] + b[3 * i + 1] * icrf.xyz_au[1] +
                         b[3 * i + 2] * icrf.xyz_au[2];
        CHECK(std::fabs(x - j2k.xyz_au[i]) < 1e-12);
    }

    // True minus mean ecliptic longitude of date = dpsi; latitude equal.
    o.coords = Coords::Ecliptic;
    o.frame = Frame::MeanOfDate;
    const Position mean = calc(o);
    o.frame = Frame::TrueOfDate;
    const Position tru = calc(o);
    double dpsi, deps;
    frames::nutation(jd_tt, dpsi, deps);
    CHECK(std::fabs(wrap180(tru.lon_deg - mean.lon_deg) * kDeg2Rad - dpsi) < 1e-12);
    CHECK(std::fabs(tru.lat_deg - mean.lat_deg) < 1e-12);

    // Equatorial of date: RA/Dec agree with rotating the true ecliptic
    // vector back by the true obliquity.
    o.coords = Coords::Equatorial;
    const Position eq = calc(o);
    const double eps = frames::mean_obliquity(jd_tt) + deps;
    const double c = std::cos(eps), s = std::sin(eps);
    const double y = c * tru.xyz_au[1] - s * tru.xyz_au[2];
    const double z = s * tru.xyz_au[1] + c * tru.xyz_au[2];
    CHECK(std::fabs(tru.xyz_au[0] - eq.xyz_au[0]) < 1e-13);
    CHECK(std::fabs(y - eq.xyz_au[1]) < 1e-13);
    CHECK(std::fabs(z - eq.xyz_au[2]) < 1e-13);
}

TEST_CASE("engine_synthetic_centers_and_errors") {
    TempFile tf("engine-err");
    Engine e = open_synthetic(tf);
    const double jd_tt = 2451545.0;
    CalcOptions o = CalcOptions::geometric();
    o.frame = Frame::ICRF;
    o.coords = Coords::Equatorial;

    // Heliocentric Earth = Earth - Sun; barycentric Sun = Sun.
    o.center = Center::Heliocentric;
    auto h = e.calc(body::kEarth, jd_tt, o);
    CHECK(h.ok());
    const double et = et_of_tdb(time::tdb_from_tt(jd_tt));
    double g[6], s[6];
    linear_state(kBodies[1], et, g);
    linear_state(kBodies[0], et, s);
    for (int i = 0; i < 3; ++i)
        CHECK(std::fabs(h.value().pos.xyz_au[i] * kAuKm - (g[i] - s[i])) < 1e-6);
    o.center = Center::Barycentric;
    auto sb = e.calc(body::kSun, jd_tt, o);
    CHECK(sb.ok());
    for (int i = 0; i < 3; ++i)
        CHECK(std::fabs(sb.value().pos.xyz_au[i] * kAuKm - s[i]) < 1e-9);

    // Topocentric: the observer sits within an Earth radius of the geocentre.
    CalcOptions t = o;
    t.center = Center::Topocentric;
    t.site = {8.55 * kDeg2Rad, 47.37 * kDeg2Rad, 500.0};
    o.center = Center::Geocentric;
    auto rg = e.calc(body::kJupiter, jd_tt, o);
    auto rt = e.calc(body::kJupiter, jd_tt, t);
    CHECK(rg.ok());
    CHECK(rt.ok());
    const Position geo = rg.ok() ? rg.value().pos : Position{};
    const Position top = rt.ok() ? rt.value().pos : Position{};
    double dd[3];
    for (int i = 0; i < 3; ++i)
        dd[i] = (geo.xyz_au[i] - top.xyz_au[i]) * kAuKm;
    CHECK(norm3(dd) > 6350.0);
    CHECK(norm3(dd) < 6380.0);

    // Body-centred: from the Sun and from the Earth it is exactly the
    // heliocentric and geocentric answer; from Jupiter the geometric vector
    // is Earth - Jupiter.
    {
        CalcOptions ob = o;
        ob.center = Center::Body;
        ob.center_body = body::kSun;
        const auto from_sun = e.calc(body::kEarth, jd_tt, ob);
        REQUIRE(from_sun.ok());
        for (int i = 0; i < 3; ++i)
            CHECK(from_sun.value().pos.xyz_au[i] == h.value().pos.xyz_au[i]);
        CalcOptions geo = CalcOptions::apparent();
        ob = geo;
        ob.center = Center::Body;
        ob.center_body = body::kEarth;
        const auto a = e.calc(body::kJupiter, jd_tt, geo), b = e.calc(body::kJupiter, jd_tt, ob);
        REQUIRE(a.ok());
        REQUIRE(b.ok());
        CHECK(a.value().pos.lon_deg == b.value().pos.lon_deg);
        CHECK(a.value().pos.lat_deg == b.value().pos.lat_deg);
        CHECK(a.value().pos.lon_speed == b.value().pos.lon_speed);
        ob = o;
        ob.center = Center::Body;
        ob.center_body = body::kJupiter;
        const auto j = e.calc(body::kEarth, jd_tt, ob);
        REQUIRE(j.ok());
        double jup[6];
        linear_state(kBodies[2], et, jup);
        for (int i = 0; i < 3; ++i)
            CHECK(std::fabs(j.value().pos.xyz_au[i] * kAuKm - (g[i] - jup[i])) < 1e-6);
        CHECK(e.calc(body::kJupiter, jd_tt, ob).error().code == ErrorCode::ArgumentError);
        ob.center_body = body::kMars; // not in the synthetic kernel
        CHECK(e.calc(body::kEarth, jd_tt, ob).error().code == ErrorCode::NotFound);
    }

    // Errors.
    o.center = Center::Geocentric;
    CHECK(e.calc(body::kEarth, jd_tt, o).error().code == ErrorCode::ArgumentError);
    o.center = Center::Heliocentric;
    CHECK(e.calc(body::kSun, jd_tt, o).error().code == ErrorCode::ArgumentError);
    o.center = Center::Barycentric;
    CHECK(e.calc(body::kSolarSystemBary, jd_tt, o).error().code == ErrorCode::ArgumentError);
    o.center = Center::Geocentric;
    CHECK(e.calc(body::kMars, jd_tt, o).error().code == ErrorCode::NotFound);
    CHECK(e.calc(body::kJupiter, NAN, o).error().code == ErrorCode::ArgumentError);
    CHECK(!e.calc(body::kJupiter, jd_tt + 100.0 * 365.25, o).ok()); // outside coverage

    Engine closed;
    CHECK(closed.calc(body::kSun, jd_tt).error().code == ErrorCode::ArgumentError);
    CHECK(Engine::open("/nonexistent/prometheia.bsp").error().code == ErrorCode::IoError);
    const fs::path junk =
        fs::temp_directory_path() / ("prometheia-junk-" + std::to_string(::getpid()) + ".bin");
    {
        FILE* fp = std::fopen(junk.c_str(), "wb");
        std::fputs("definitely not an ephemeris", fp);
        std::fclose(fp);
    }
    CHECK(!Engine::open(junk.string()).ok());
    fs::remove(junk);
}

TEST_CASE("engine_orbit_points_geometry") {
    // Properties any conic satisfies, on the synthetic kernel (the Earth's
    // straight-line "orbit" around the Sun is still an osculating conic).
    TempFile tf("engine-orbit");
    Engine e = open_synthetic(tf);
    const double jd = 2451600.5;
    CalcOptions o = CalcOptions::geometric();
    o.center = Center::Heliocentric;
    o.frame = Frame::MeanOfDate;
    o.speed = false;
    const auto at = [&](OrbitPoint point) {
        auto r = e.calc_orbit_point(body::kEarth, point, OrbitElements::Osculating, jd, o);
        REQUIRE_MESSAGE(r.ok(), r.error().message);
        return r.value();
    };
    const CalcResult asc = at(OrbitPoint::AscendingNode), desc = at(OrbitPoint::DescendingNode);
    // Nodes sit on the (mean) ecliptic of date, opposite each other as seen
    // from the Sun.
    CHECK(std::fabs(asc.pos.lat_deg) < 1e-9);
    CHECK(std::fabs(desc.pos.lat_deg) < 1e-9);
    CHECK(std::fabs(std::fmod(desc.pos.lon_deg - asc.pos.lon_deg + 720.0, 360.0) - 180.0) < 1e-9);
    // The frame changes the coordinates, not the point (3.5a, amended
    // 2026-09-18): the node asked in ICRF, rotated into the mean ecliptic of
    // date by the public frame matrices, is the node asked in that frame.
    {
        CalcOptions oi = o;
        oi.frame = Frame::ICRF;
        oi.coords = Coords::Equatorial;
        auto ri = e.calc_orbit_point(body::kEarth, OrbitPoint::AscendingNode,
                                     OrbitElements::Osculating, jd, oi);
        REQUIRE(ri.ok());
        double ecl[9], bias[9], v[3] = {0, 0, 0};
        frames::mean_ecliptic_of_date_matrix(jd, ecl);
        frames::frame_bias_matrix(bias);
        const double* x = ri.value().pos.xyz_au;
        for (int r = 0; r < 3; ++r)
            for (int c = 0; c < 3; ++c)
                for (int k = 0; k < 3; ++k)
                    v[r] += ecl[3 * r + k] * bias[3 * k + c] * x[c];
        const double* want = asc.pos.xyz_au;
        const double n = std::sqrt(want[0] * want[0] + want[1] * want[1] + want[2] * want[2]);
        for (int k = 0; k < 3; ++k)
            CHECK(std::fabs(v[k] - want[k]) < 1e-12 * n);
    }
    const CalcResult peri = at(OrbitPoint::Perihelion);
    // The body's own state and the conic through it: vis-viva gives a, the
    // apsides give q and Q, and they must agree.
    CalcOptions os = o;
    os.speed = true;
    os.frame = Frame::J2000; // vis-viva needs an inertial frame's velocity
    const auto state = e.calc(body::kEarth, jd, os);
    REQUIRE(state.ok());
    const double* x = state.value().pos.xyz_au;
    const double* v = state.value().pos.vel_au_day;
    const double r = std::sqrt(x[0] * x[0] + x[1] * x[1] + x[2] * x[2]);
    const double v2 = v[0] * v[0] + v[1] * v[1] + v[2] * v[2];
    const double mu = 2.9591220828559115e-04 + 8.887692445125634e-10; // GM Sun + Earth, AU^3/d^2
    const double a = 1.0 / (2.0 / r - v2 / mu);
    if (a > 0.0) {
        const CalcResult aph = at(OrbitPoint::Aphelion);
        CHECK(std::fabs((peri.pos.dist_au + aph.pos.dist_au) / 2.0 - a) < 1e-9 * a);
        const double dot = peri.pos.xyz_au[0] * aph.pos.xyz_au[0] +
                           peri.pos.xyz_au[1] * aph.pos.xyz_au[1] +
                           peri.pos.xyz_au[2] * aph.pos.xyz_au[2];
        CHECK(std::fabs(dot / (peri.pos.dist_au * aph.pos.dist_au) + 1.0) < 1e-12);
    } else {
        CHECK(
            e.calc_orbit_point(body::kEarth, OrbitPoint::Aphelion, OrbitElements::Osculating, jd, o)
                .error()
                .code == ErrorCode::ArgumentError);
    }
    CHECK(peri.pos.dist_au <= r + 1e-12);
    CHECK(!peri.sigma_arcsec.has_value());

    // Errors: the Sun has no heliocentric orbit; not open.
    CHECK(e.calc_orbit_point(body::kSun, OrbitPoint::Perihelion, OrbitElements::Osculating, jd, o)
              .error()
              .code == ErrorCode::ArgumentError);
    Engine closed;
    CHECK(
        !closed
             .calc_orbit_point(body::kEarth, OrbitPoint::Perihelion, OrbitElements::Osculating, jd)
             .ok());
}

TEST_CASE("engine_calc_ut_uses_delta_t") {
    TempFile tf("engine-ut");
    Engine e = open_synthetic(tf);
    struct Fixed final : time::DeltaTModel {
        double delta_t_seconds(double) const override { return 100.0; }
    } fixed;
    e.set_delta_t_model(&fixed);
    CalcOptions o = CalcOptions::geometric();
    const double jd_ut = 2455000.5;
    auto a = e.calc_ut(body::kJupiter, jd_ut, o);
    auto b = e.calc(body::kJupiter, jd_ut + 100.0 / 86400.0, o);
    CHECK(a.ok());
    CHECK(b.ok());
    CHECK(a.ok());
    CHECK(b.ok());
    CHECK(a.value().pos.lon_deg == b.value().pos.lon_deg);
    e.set_delta_t_model(nullptr); // default model again
    auto c = e.calc_ut(body::kJupiter, jd_ut, o);
    CHECK(c.ok());
    CHECK(c.value().pos.lon_deg != a.value().pos.lon_deg);
}

TEST_CASE("ayanamsa_functions_consistency") {
    // The true ayanamsha is the mean plus the nutation in longitude; a
    // user anchor placed at a mode's mean value reproduces that mode;
    // the mean rate is the IAU 2006 precession in longitude; unknown
    // modes are absent.
    const double t = 2451234.5;
    for (int mode : {0, 1}) {
        auto a = frames::ayanamsa(mode, t);
        CHECK(a.has_value());
        double dpsi, deps;
        frames::nutation(t, dpsi, deps);
        CHECK(std::fabs(a->true_deg - a->mean_deg - dpsi / kDeg2Rad) < 1e-12);

        const double t_ref = 2450600.5;
        auto ref = frames::ayanamsa(mode, t_ref);
        auto anchored = frames::ayanamsa_anchored(t_ref, ref->mean_deg, t);
        CHECK(std::fabs(anchored.mean_deg - a->mean_deg) < 1e-12);
        CHECK(std::fabs(anchored.true_deg - a->true_deg) < 1e-12);
    }
    CHECK(!frames::ayanamsa(7, t).has_value());

    // ~50.29"/yr at J2000, quadratic in T.
    auto lo = frames::ayanamsa(0, kJ2000 - 1826.25);
    auto hi = frames::ayanamsa(0, kJ2000 + 1826.25);
    const double rate_as = (hi->mean_deg - lo->mean_deg) / 10.0 * 3600.0;
    std::printf("  d(mean ayanamsha)/dt at J2000: %.4f\"/yr\n", rate_as);
    CHECK(rate_as > 50.27);
    CHECK(rate_as < 50.31);
}

TEST_CASE("sidereal_output_consistency") {
    TempFile tf("engine-sid");
    Engine e = open_synthetic(tf);
    const double t = kJ2000 + 1234.5;

    // Sidereal ecliptic of date = tropical minus the true ayanamsha,
    // latitude and distance untouched; the reported ayanamsa is the
    // applied shift; the rates carry the ayanamsha motion.
    CalcOptions trop = CalcOptions::apparent();
    CalcOptions sid = trop;
    sid.sidereal = SiderealMode::Lahiri;
    auto tr = e.calc(body::kSun, t, trop);
    auto sd = e.calc(body::kSun, t, sid);
    CHECK(tr.ok());
    CHECK(sd.ok());
    auto aya = frames::ayanamsa(1, t);
    CHECK(sd.value().ayanamsa_deg.has_value());
    CHECK(std::fabs(*sd.value().ayanamsa_deg - aya->true_deg) < 1e-12);
    CHECK(std::fabs(sd.value().pos.lon_deg - wrap360(tr.value().pos.lon_deg - aya->true_deg)) <
          1e-12);
    // The rotation preserves latitude and distance to rounding.
    CHECK(std::fabs(sd.value().pos.lat_deg - tr.value().pos.lat_deg) < 1e-12);
    CHECK(std::fabs(sd.value().pos.dist_au - tr.value().pos.dist_au) <
          1e-12 * tr.value().pos.dist_au);

    const double h = 0.01;
    auto am = frames::ayanamsa(1, t - h), ap = frames::ayanamsa(1, t + h);
    const double daya = (ap->true_deg - am->true_deg) / (2 * h);
    // The gate allows the nutation curvature between this window and
    // the engine's +/-0.001 day differencing window.
    CHECK(std::fabs((tr.value().pos.lon_speed - sd.value().pos.lon_speed) - daya) < 1e-8);
    CHECK(std::fabs(sd.value().pos.lat_speed - tr.value().pos.lat_speed) < 1e-12);

    // Equatorial sidereal output: the same longitude rotation about
    // the ecliptic pole, i.e. (lon - ayanamsa, lat) converted with the
    // true obliquity.
    CalcOptions sideq = sid;
    sideq.coords = Coords::Equatorial;
    auto sq = e.calc(body::kSun, t, sideq);
    CHECK(sq.ok());
    double dpsi, deps;
    frames::nutation(t, dpsi, deps);
    const double et = frames::mean_obliquity(t) + deps; // radians, true
    const double lon = sd.value().pos.lon_deg * kDeg2Rad, lat = sd.value().pos.lat_deg * kDeg2Rad;
    const double ce = std::cos(et), se = std::sin(et);
    const double x = std::cos(lat) * std::cos(lon), y = std::cos(lat) * std::sin(lon),
                 z = std::sin(lat);
    const double ra = std::atan2(y * ce - z * se, x) / kDeg2Rad;
    const double dec = std::asin(y * se + z * ce) / kDeg2Rad;
    CHECK(std::fabs(wrap180(sq.value().pos.lon_deg - wrap360(ra))) < 1e-9);
    CHECK(std::fabs(sq.value().pos.lat_deg - dec) < 1e-9);

    // The mean-of-date frames shift by the mean ayanamsha (no nutation
    // on either side of the subtraction).
    CalcOptions mod = trop, mods = trop;
    mod.frame = mods.frame = Frame::MeanOfDate;
    mods.sidereal = SiderealMode::Lahiri;
    auto mm = e.calc(body::kSun, t, mod);
    auto ms = e.calc(body::kSun, t, mods);
    CHECK(mm.ok());
    CHECK(ms.ok());
    CHECK(std::fabs(ms.value().pos.lon_deg - wrap360(mm.value().pos.lon_deg - aya->mean_deg)) <
          1e-12);
    CHECK(std::fabs(*ms.value().ayanamsa_deg - aya->mean_deg) < 1e-12);

    // J2000 sidereal keeps one fixed offset from J2000 tropical (the
    // zodiac's zero point is fixed on the mean ecliptic of J2000).
    CalcOptions j2 = CalcOptions::geometric();
    j2.frame = Frame::J2000;
    CalcOptions j2s = j2;
    j2s.sidereal = SiderealMode::FaganBradley;
    j2.speed = j2s.speed = false;
    double offs0 = 0.0;
    for (double dt : {0.0, 400.0, -3000.0}) {
        auto a = e.calc(body::kJupiter, t + dt, j2);
        auto b = e.calc(body::kJupiter, t + dt, j2s);
        CHECK(a.ok());
        CHECK(b.ok());
        CHECK(b.value().ayanamsa_deg.has_value());
        const double off = wrap180(b.value().pos.lon_deg - a.value().pos.lon_deg);
        if (dt == 0.0)
            offs0 = off;
        CHECK(std::fabs(off - offs0) < 1e-9);
    }

    // Error paths: unknown mode, non-finite user anchor.
    CalcOptions bad = trop;
    bad.sidereal = static_cast<SiderealMode>(7);
    CHECK(!e.calc(body::kSun, t, bad).ok());
    bad = trop;
    bad.sidereal = SiderealMode::User;
    bad.sidereal_ayanamsa_deg = std::nan("");
    CHECK(!e.calc(body::kSun, t, bad).ok());
}

// ---------------------------------------------------------------------------
// Part B: DE440 against the swetest fixtures.
// ---------------------------------------------------------------------------

enum class Mode {
    Apparent,
    ApparentEquatorial,
    ApparentJ2000,
    GeometricJ2000,
    BarycentricJ2000,
    HeliocentricJ2000,
    Topocentric,
};

#include "engine_fixtures.inc"
#include "sidereal_fixtures.inc"

std::string env_or(const char* var, const std::string& fallback) {
    const char* env = std::getenv(var);
    return env && *env ? std::string(env) : fallback;
}

bool available(const std::string& path, const char* var) {
    if (fs::exists(path))
        return true;
    std::printf("  [SKIP] '%s' not found (set %s to enable)\n", path.c_str(), var);
    return false;
}

const std::string kDe440Path =
    env_or("PROMETHEIA_DE440", std::string(PROMETHEIA_SOURCE_DIR) + "/ephe/linux_p1550p2650.440");
const std::string kDe440sPath =
    env_or("PROMETHEIA_DE440S", std::string(PROMETHEIA_SOURCE_DIR) + "/ephe/de440s.bsp");

struct FixedDeltaT final : time::DeltaTModel {
    double seconds = 0.0;
    double delta_t_seconds(double) const override { return seconds; }
};

CalcOptions options_for(Mode m) {
    CalcOptions o;
    switch (m) {
    case Mode::Apparent:
        break;
    case Mode::ApparentEquatorial:
        o.coords = Coords::Equatorial;
        break;
    case Mode::ApparentJ2000:
        o.frame = Frame::J2000;
        break;
    case Mode::GeometricJ2000:
        o = CalcOptions::geometric();
        o.frame = Frame::J2000;
        break;
    case Mode::BarycentricJ2000:
        o = CalcOptions::geometric();
        o.frame = Frame::J2000;
        o.center = Center::Barycentric;
        break;
    case Mode::HeliocentricJ2000:
        o = CalcOptions::geometric();
        o.frame = Frame::J2000;
        o.center = Center::Heliocentric;
        break;
    case Mode::Topocentric:
        o.center = Center::Topocentric;
        o.site = {8.55 * kDeg2Rad, 47.37 * kDeg2Rad, 500.0};
        break;
    }
    o.speed = false;
    return o;
}

const char* mode_name(Mode m) {
    static const char* names[] = {"apparent (true ecliptic of date)",
                                  "apparent (true equator of date)",
                                  "apparent (J2000 ecliptic)",
                                  "geometric (J2000 ecliptic)",
                                  "barycentric geometric (J2000)",
                                  "heliocentric geometric (J2000)",
                                  "topocentric apparent"};
    return names[int(m)];
}

TEST_CASE("de440_engine_matches_swetest") {
    if (!available(kDe440Path, "PROMETHEIA_DE440"))
        return;
    auto opened = Engine::open(kDe440Path);
    CHECK(opened.ok());
    if (!opened)
        return;
    Engine e = std::move(opened).value();
    CHECK(e.source() == "JPL DE440 binary");
    FixedDeltaT dt;
    e.set_delta_t_model(&dt);

    struct Worst {
        double planets_as = 0.0, moon_as = 0.0, dist_au = 0.0, moon_dist_au = 0.0;
    };
    Worst worst[7];
    for (const Fixture& f : kFixtures) {
        for (const DeltaTFixture& d : kSweDeltaT)
            if (d.jd_tt == f.jd_tt)
                dt.seconds = d.seconds;
        auto r = e.calc(f.body, f.jd_tt, options_for(f.mode));
        CHECK(r.ok());
        if (!r) {
            std::printf("  body %d: %s\n", f.body, r.error().message.c_str());
            continue;
        }
        const Position& p = r.value().pos;
        const double sep = sep_as(p.lon_deg, p.lat_deg, f.a, f.b);
        const double dr = std::fabs(p.dist_au - f.r);
        Worst& w = worst[int(f.mode)];
        if (f.body == body::kMoon) {
            w.moon_as = std::max(w.moon_as, sep);
            w.moon_dist_au = std::max(w.moon_dist_au, dr);
        } else {
            w.planets_as = std::max(w.planets_as, sep);
            w.dist_au = std::max(w.dist_au, dr);
        }
    }
    for (int m = 0; m < 7; ++m) {
        const Worst& w = worst[m];
        std::printf("  %-34s Sun/planets %.4f\"  Moon %.4f\"  |dr| %.1e / %.1e AU\n",
                    mode_name(Mode(m)), w.planets_as, w.moon_as, w.dist_au, w.moon_dist_au);
        const bool date_frame = Mode(m) == Mode::Apparent || Mode(m) == Mode::ApparentEquatorial ||
                                Mode(m) == Mode::Topocentric;
        // J2000-frame modes isolate the correction pipeline: SWE prints
        // 0.0001" and the Moon carries ~1 mas of unexplained difference.
        // Date frames add SWE's non-IAU-2006 long-term precession (~2 mas
        // over 1800-2100). SWE rotates the topocentric site with the mean
        // pole, ~0.1" at the Moon (docs/ENGINE.md).
        CHECK(w.planets_as < (date_frame ? 0.005 : 0.0005));
        CHECK(w.moon_as < (Mode(m) == Mode::Topocentric ? 0.25 : (date_frame ? 0.005 : 0.003)));
        CHECK(w.dist_au < 2e-9);
        CHECK(w.moon_dist_au < (Mode(m) == Mode::Topocentric ? 5e-9 : 2e-9));
    }
}

TEST_CASE("de440_vondrak_precession_matches_swetest") {
    // The Swiss Ephemeris' default long-term precession is Vondrak et al.
    // (2011). Selecting it here shrinks our date-frame residuals against its
    // output over 1800-2100 (ecliptic of date 2.5 -> 1.7 mas, equator of
    // date 3.1 -> 1.9 mas); the ~2 mas that remain, and the ayanamshas'
    // 2.6 mas, are SWE conventions beyond precession (obliquity/nutation
    // details), not the precession model.
    if (!available(kDe440Path, "PROMETHEIA_DE440"))
        return;
    auto opened = Engine::open(kDe440Path);
    REQUIRE(opened.ok());
    Engine e = std::move(opened).value();
    FixedDeltaT dt;
    e.set_delta_t_model(&dt);
    double worst[2] = {0.0, 0.0}, worst_iau[2] = {0.0, 0.0};
    for (const Fixture& f : kFixtures) {
        if (f.mode != Mode::Apparent && f.mode != Mode::ApparentEquatorial)
            continue;
        for (const DeltaTFixture& d : kSweDeltaT)
            if (d.jd_tt == f.jd_tt)
                dt.seconds = d.seconds;
        CalcOptions o = options_for(f.mode);
        auto iau = e.calc(f.body, f.jd_tt, o);
        o.precession = Precession::Vondrak2011;
        auto ltp = e.calc(f.body, f.jd_tt, o);
        REQUIRE(iau.ok());
        REQUIRE(ltp.ok());
        const int k = f.mode == Mode::Apparent ? 0 : 1;
        worst[k] =
            std::max(worst[k], sep_as(ltp.value().pos.lon_deg, ltp.value().pos.lat_deg, f.a, f.b));
        worst_iau[k] = std::max(worst_iau[k],
                                sep_as(iau.value().pos.lon_deg, iau.value().pos.lat_deg, f.a, f.b));
    }
    double worst_ayan = 0.0, worst_ayan_iau = 0.0;
    for (const AyanamsaFixture& f : kAyanamsaFixtures) {
        auto a = frames::ayanamsa(f.mode, f.jd_tt, frames::PrecessionModel::Vondrak2011);
        auto b = frames::ayanamsa(f.mode, f.jd_tt);
        REQUIRE(a.has_value());
        REQUIRE(b.has_value());
        worst_ayan = std::max(worst_ayan, std::fabs(a->true_deg - f.deg) * 3600.0);
        worst_ayan_iau = std::max(worst_ayan_iau, std::fabs(b->true_deg - f.deg) * 3600.0);
    }
    std::printf("  vs swetest, IAU 2006 -> Vondrak 2011: ecliptic of date %.4f\" -> %.4f\", "
                "equator of date %.4f\" -> %.4f\", ayanamsha %.4f\" -> %.4f\"\n",
                worst_iau[0], worst[0], worst_iau[1], worst[1], worst_ayan_iau, worst_ayan);
    CHECK(worst[0] < 0.0025);
    CHECK(worst[1] < 0.0025);
    CHECK(worst[0] < worst_iau[0]);
    CHECK(worst[1] < worst_iau[1]);
    CHECK(worst_ayan < 0.005);
}

TEST_CASE("de440_engine_rates_match_differenced_swetest") {
    if (!available(kDe440Path, "PROMETHEIA_DE440"))
        return;
    auto opened = Engine::open(kDe440Path);
    if (!opened)
        return;
    Engine e = std::move(opened).value();
    double worst_lon = 0.0, worst_lat = 0.0, worst_dist = 0.0;
    for (const SpeedFixture& f : kSpeedFixtures) {
        auto r = e.calc(f.body, f.jd_tt);
        CHECK(r.ok());
        if (!r)
            continue;
        const Position& p = r.value().pos;
        const double dlon = wrap180(f.a1 - f.a0) / (2.0 * kSpeedH);
        const double dlat = (f.b1 - f.b0) / (2.0 * kSpeedH);
        const double ddist = (f.r1 - f.r0) / (2.0 * kSpeedH);
        worst_lon = std::max(worst_lon, std::fabs(p.lon_speed - dlon));
        worst_lat = std::max(worst_lat, std::fabs(p.lat_speed - dlat));
        worst_dist = std::max(worst_dist, std::fabs(p.dist_speed - ddist));
    }
    std::printf("  rate residuals: lon %.1e deg/day, lat %.1e deg/day, dist %.1e AU/day\n",
                worst_lon, worst_lat, worst_dist);
    // Differenced 0.0001" fixtures over 0.02 day resolve ~1.4e-6 deg/day.
    CHECK(worst_lon < 5e-6);
    CHECK(worst_lat < 5e-6);
    CHECK(worst_dist < 1e-7);
}

// The fixed sidereal planes (protocol v4 A.8), by their definitions.
TEST_CASE("sidereal_fixed_planes") {
    TempFile tf("engine-sidplane");
    Engine e = open_synthetic(tf);
    const double t = kJ2000 + 1234.5;
    const auto unit_of = [](double lon, double lat, double u[3]) {
        const double a = lon * M_PI / 180.0, b = lat * M_PI / 180.0;
        u[0] = std::cos(b) * std::cos(a);
        u[1] = std::cos(b) * std::sin(a);
        u[2] = std::sin(b);
    };

    // The anchor ecliptic at its own epoch is the mean ecliptic of date
    // there, and A0 is the mean ayanamsha there: a user zodiac anchored at
    // t answers the same on plane 1 as on plane 0 in the mean frame.
    CalcOptions date = CalcOptions::apparent();
    date.frame = Frame::MeanOfDate;
    date.sidereal = SiderealMode::User;
    date.sidereal_epoch_jtdb = t;
    date.sidereal_ayanamsa_deg = 23.5;
    CalcOptions anchor = date;
    anchor.sidereal_plane = SiderealPlane::EclipticOfAnchor;
    for (int id : {body::kSun, body::kJupiter}) {
        auto a = e.calc(id, t, date), b = e.calc(id, t, anchor);
        INFO(id, " ", a.ok() ? "" : a.error().message);
        REQUIRE(a.ok());
        REQUIRE(b.ok());
        CHECK(std::fabs(wrap360(b.value().pos.lon_deg - a.value().pos.lon_deg + 180.0) - 180.0) <
              1e-10);
        CHECK(std::fabs(b.value().pos.lat_deg - a.value().pos.lat_deg) < 1e-10);
        CHECK(b.value().ayanamsa_deg.value_or(-1) == 23.5);
    }

    // The invariable plane: latitude is the angle from the plane, so its
    // sine is the ICRF direction's component along the pole; the reported
    // ayanamsa is the anchor's A0.
    CalcOptions icrf = CalcOptions::apparent();
    icrf.frame = Frame::ICRF;
    icrf.coords = Coords::Equatorial;
    CalcOptions inv = CalcOptions::apparent();
    inv.sidereal = SiderealMode::Lahiri;
    inv.sidereal_plane = SiderealPlane::Invariable;
    const auto anchor_lahiri = frames::ayanamsa_anchor(1);
    REQUIRE(anchor_lahiri.has_value());
    for (int id : {body::kSun, body::kJupiter}) {
        auto q = e.calc(id, t, icrf), r = e.calc(id, t, inv);
        REQUIRE(q.ok());
        REQUIRE(r.ok());
        double u[3];
        unit_of(q.value().pos.lon_deg, q.value().pos.lat_deg, u);
        const double* n = frames::kInvariablePoleIcrf;
        CHECK(std::fabs(std::sin(r.value().pos.lat_deg * M_PI / 180.0) -
                        (u[0] * n[0] + u[1] * n[1] + u[2] * n[2])) < 1e-12);
        CHECK(std::fabs(r.value().pos.dist_au - q.value().pos.dist_au) <
              1e-12 * q.value().pos.dist_au);
        CHECK(r.value().ayanamsa_deg.value_or(-1) == anchor_lahiri->mean0_deg);
    }

    // The invariable longitude's origin, built independently: the zero point
    // (longitude A0 on the mean ecliptic of t0) through the public frames
    // matrices, projected onto the plane; a body's longitude is the signed
    // angle from it to the body's own projection, about the pole.
    {
        double ecl[9], bias[9], m0[9];
        frames::mean_ecliptic_of_date_matrix(anchor_lahiri->t0_jtdb, ecl);
        frames::frame_bias_matrix(bias);
        for (int r = 0; r < 3; ++r)
            for (int c = 0; c < 3; ++c)
                m0[3 * r + c] = ecl[3 * r] * bias[c] + ecl[3 * r + 1] * bias[3 + c] +
                                ecl[3 * r + 2] * bias[6 + c];
        const double a0 = anchor_lahiri->mean0_deg * M_PI / 180.0;
        const double ze[3] = {std::cos(a0), std::sin(a0), 0.0};
        double z[3];
        for (int c = 0; c < 3; ++c)
            z[c] = m0[c] * ze[0] + m0[3 + c] * ze[1] + m0[6 + c] * ze[2]; // transpose
        const double* n = frames::kInvariablePoleIcrf;
        const auto project = [&](const double v[3], double out[3]) {
            const double d = v[0] * n[0] + v[1] * n[1] + v[2] * n[2];
            for (int i = 0; i < 3; ++i)
                out[i] = v[i] - d * n[i];
        };
        double pz[3];
        project(z, pz);
        for (int id : {body::kSun, body::kJupiter}) {
            auto q = e.calc(id, t, icrf), r = e.calc(id, t, inv);
            REQUIRE((q.ok() && r.ok()));
            double u[3], pu[3];
            unit_of(q.value().pos.lon_deg, q.value().pos.lat_deg, u);
            project(u, pu);
            const double cx[3] = {pz[1] * pu[2] - pz[2] * pu[1], pz[2] * pu[0] - pz[0] * pu[2],
                                  pz[0] * pu[1] - pz[1] * pu[0]};
            const double lon = std::atan2(cx[0] * n[0] + cx[1] * n[1] + cx[2] * n[2],
                                          pz[0] * pu[0] + pz[1] * pu[1] + pz[2] * pu[2]) *
                               180.0 / M_PI;
            CHECK(std::fabs(wrap360(r.value().pos.lon_deg - lon + 180.0) - 180.0) < 1e-9);
        }
    }

    // A fixed plane's rates are the positions' own derivative.
    const double h = 0.01;
    auto m = e.calc(body::kJupiter, t - h, inv), c = e.calc(body::kJupiter, t, inv),
         p = e.calc(body::kJupiter, t + h, inv);
    REQUIRE((m.ok() && c.ok() && p.ok()));
    const double dlon =
        (wrap360(p.value().pos.lon_deg - m.value().pos.lon_deg + 180.0) - 180.0) / (2 * h);
    CHECK(std::fabs(dlon - c.value().pos.lon_speed) < 1e-6);
    CHECK(std::fabs((p.value().pos.lat_deg - m.value().pos.lat_deg) / (2 * h) -
                    c.value().pos.lat_speed) < 1e-6);

    // A fixed plane is an ecliptic: equatorial coordinates are refused.
    CalcOptions eq = inv;
    eq.coords = Coords::Equatorial;
    CHECK_FALSE(e.calc(body::kSun, t, eq).ok());
    // The ecliptic of date is untouched by the option when tropical.
    CalcOptions trop = CalcOptions::apparent();
    CalcOptions trop_plane = trop;
    trop_plane.sidereal_plane = SiderealPlane::Invariable;
    auto t1 = e.calc(body::kSun, t, trop), t2 = e.calc(body::kSun, t, trop_plane);
    REQUIRE((t1.ok() && t2.ok()));
    CHECK(t1.value().pos.lon_deg == t2.value().pos.lon_deg);
}

// frames::kInvariablePoleIcrf, recomputed: the unit normal to the total
// angular momentum of the Sun, the planetary-system barycentres and Pluto
// from DE440's states and GM constants, at J2000 and, as a check that the
// mass set conserves it, at 1800 and 2200.
#include "zodiac_fixtures.inc"

// The zodiacs defined at the instant (docs/FRAMES.md): their true ayanamsha
// against ERFA, built by other routes (tools/gen/gen_zodiac_fixtures.py).
TEST_CASE("zodiacs_at_the_instant_match_erfa") {
    TempFile tf("engine-instant-zodiac");
    Engine e = open_synthetic(tf);
    // The ayanamsha does not depend on the object: a star seen from the
    // barycentre needs no ephemeris coverage, which the synthetic kernel
    // lacks at 1900 and 2100.
    auto star = stars::find("Vega");
    REQUIRE(star.ok());
    double worst = 0.0, worst_node = 0.0;
    for (const ZodiacFixture& f : kZodiacFixtures) {
        CalcOptions o = CalcOptions::geometric();
        o.center = Center::Barycentric;
        o.frame = Frame::TrueOfDate;
        o.sidereal = SiderealMode(f.mode);
        auto r = e.calc_star(star.value(), f.jd_tt, o);
        INFO("mode ", f.mode, " jd ", f.jd_tt, " ", r.ok() ? "" : r.error().message);
        REQUIRE(r.ok());
        const double d = std::fabs(*r.value().ayanamsa_deg - f.true_deg) * 3600.0;
        // The IAU 1958 pole: the engine takes Liu et al.'s ICRS value (their
        // eq. 19), ERFA the Hipparcos catalogue's transfer; they differ by
        // milliarcseconds, which the node's shallow crossing magnifies.
        if (f.mode == int(SiderealMode::GalacticEquatorIau1958))
            worst_node = std::max(worst_node, d);
        else
            worst = std::max(worst, d);
        // The mean ayanamsha (the mean frame's) is the true one less the
        // nutation in longitude, as for the anchored zodiacs.
        CalcOptions mean = o;
        mean.frame = Frame::MeanOfDate;
        auto rm = e.calc_star(star.value(), f.jd_tt, mean);
        REQUIRE(rm.ok());
        double dpsi, deps;
        frames::nutation(f.jd_tt, dpsi, deps);
        CHECK(std::fabs(*rm.value().ayanamsa_deg - (*r.value().ayanamsa_deg - dpsi * 180.0 / kPi)) *
                  3600.0 <
              1e-9);
    }
    MESSAGE("worst against ERFA: ", worst, "\" (IAU 1958 node ", worst_node, "\")");
    CHECK(worst < 0.001);
    CHECK(worst_node < 0.02);
}

// Each star zodiac, asked for its own anchor star at its true position
// (barycentric, no aberration, no deflection) on the true ecliptic of date,
// puts the star exactly where its definition does.
TEST_CASE("zodiacs_at_the_instant_hold_their_star") {
    TempFile tf("engine-instant-star");
    Engine e = open_synthetic(tf);
    const struct {
        SiderealMode mode;
        const char* star;
        double at_deg;
    } cases[] = {
        {SiderealMode::TrueCitra, "HR 5056", 180.0},
        {SiderealMode::TrueRevati, "HR 361", 359.0 + 50.0 / 60.0},
        {SiderealMode::TruePushya, "HR 3461", 106.0},
        {SiderealMode::TrueMula, "HR 6527", 240.0},
    };
    for (const auto& c : cases) {
        auto idx = stars::find(c.star);
        REQUIRE(idx.ok());
        for (double t : {2415020.5, kJ2000, 2488069.5}) {
            CalcOptions o = CalcOptions::geometric();
            o.center = Center::Barycentric;
            o.frame = Frame::TrueOfDate;
            o.sidereal = c.mode;
            auto r = e.calc_star(idx.value(), t, o);
            INFO(c.star, " at ", t, " ", r.ok() ? "" : r.error().message);
            REQUIRE(r.ok());
            double dl = r.value().pos.lon_deg - c.at_deg;
            dl -= 360.0 * std::round(dl / 360.0);
            CHECK(std::fabs(dl) * 3600.0 < 1e-6);
        }
    }
}

// Planes (3.5a, the clause for zodiacs defined at the instant): no ecliptic of
// the anchor epoch; on the invariable plane, the zero point of the instant.
TEST_CASE("zodiacs_at_the_instant_on_the_fixed_planes") {
    TempFile tf("engine-instant-planes");
    Engine e = open_synthetic(tf);
    const double t = kJ2000 + 1234.5;
    CalcOptions o;
    o.sidereal = SiderealMode::GalacticCentre0Sag;
    o.sidereal_plane = SiderealPlane::EclipticOfAnchor;
    CHECK_FALSE(e.calc(body::kSun, t, o).ok());

    // The invariable plane: the same answer as a user zodiac anchored at this
    // instant with this instant's mean ayanamsha, whose plane-2 construction
    // sidereal_fixed_planes already holds to the frame matrices.
    CalcOptions mean = o;
    mean.frame = Frame::MeanOfDate;
    mean.sidereal_plane = SiderealPlane::EclipticOfDate;
    auto m = e.calc(body::kSun, t, mean);
    REQUIRE(m.ok());
    CalcOptions inv = o;
    inv.sidereal_plane = SiderealPlane::Invariable;
    CalcOptions user = inv;
    user.sidereal = SiderealMode::User;
    user.sidereal_epoch_jtdb = t;
    user.sidereal_ayanamsa_deg = *m.value().ayanamsa_deg;
    for (int id : {body::kSun, body::kJupiter}) {
        auto a = e.calc(id, t, inv), b = e.calc(id, t, user);
        REQUIRE(a.ok());
        REQUIRE(b.ok());
        CHECK(std::fabs(a.value().pos.lon_deg - b.value().pos.lon_deg) * 3600.0 < 1e-9);
        CHECK(std::fabs(a.value().pos.lat_deg - b.value().pos.lat_deg) * 3600.0 < 1e-9);
        CHECK(*a.value().ayanamsa_deg == doctest::Approx(*m.value().ayanamsa_deg).epsilon(1e-15));
    }
}

// A site the geodetic formulas cannot place is an error, not NaN coordinates
// reported as a success (found by fuzzing prometheiad: the protocol bounds a
// site's latitude and longitude but not its height).
TEST_CASE("engine_refuses_an_impossible_site") {
    TempFile tf("engine-site");
    Engine e = open_synthetic(tf);
    CalcOptions o;
    o.center = Center::Topocentric;
    for (double h : {-563224831328256.0, -6356752.0, std::nan(""), HUGE_VAL}) {
        o.site = {0.0, 0.0, h};
        auto r = e.calc(body::kSun, kJ2000, o);
        INFO("height ", h);
        CHECK_FALSE(r.ok());
    }
    o.site = {0.0, 0.0, -6356751.0}; // just above the centre: placeable
    CHECK(e.calc(body::kSun, kJ2000, o).ok());
}

TEST_CASE("invariable_plane_from_de440") {
    if (!available(kDe440Path, "PROMETHEIA_DE440"))
        return;
    auto f = de::DeFile::open(kDe440Path);
    REQUIRE(f.ok());
    struct B {
        de::Target t;
        double gm;
    };
    const B bodies[] = {
        {de::Target::Sun, gm::kSun},         {de::Target::Mercury, gm::kMercury},
        {de::Target::Venus, gm::kVenus},     {de::Target::EarthMoonBary, gm::kEarthMoonBary},
        {de::Target::Mars, gm::kMars},       {de::Target::Jupiter, gm::kJupiter},
        {de::Target::Saturn, gm::kSaturn},   {de::Target::Uranus, gm::kUranus},
        {de::Target::Neptune, gm::kNeptune}, {de::Target::Pluto, gm::kPluto}};
    const auto pole = [&](double jd, double n[3]) {
        double L[3] = {0, 0, 0};
        for (const B& b : bodies) {
            double s[6];
            REQUIRE(f.value().relative_state(b.t, de::Target::SolarSystemBary, jd, s).ok());
            L[0] += b.gm * (s[1] * s[5] - s[2] * s[4]);
            L[1] += b.gm * (s[2] * s[3] - s[0] * s[5]);
            L[2] += b.gm * (s[0] * s[4] - s[1] * s[3]);
        }
        const double len = std::sqrt(L[0] * L[0] + L[1] * L[1] + L[2] * L[2]);
        for (int i = 0; i < 3; ++i)
            n[i] = L[i] / len;
    };
    double n[3];
    pole(kJ2000, n);
    for (int i = 0; i < 3; ++i)
        CHECK(std::fabs(n[i] - frames::kInvariablePoleIcrf[i]) < 1e-14);
    for (double jd : {2378496.5, 2524593.5}) {
        double m[3];
        pole(jd, m);
        for (int i = 0; i < 3; ++i)
            CHECK(std::fabs(m[i] - n[i]) < 1e-8);
    }
}

TEST_CASE("de440_sidereal_matches_swetest") {
    if (!available(kDe440Path, "PROMETHEIA_DE440"))
        return;
    auto opened = Engine::open(kDe440Path);
    if (!opened)
        return;
    Engine e = std::move(opened).value();

    // The ayanamshas themselves: our IAU 2006 p_A + IAU 2000A series
    // against the -ay<m> output (SWE's precession is its long-term
    // model; the residual is a time-only difference, identical for both
    // modes, <= 0.08" over 1800-2200).
    double worst_ayan = 0.0, worst_ayan_1800 = 0.0;
    for (const AyanamsaFixture& f : kAyanamsaFixtures) {
        auto a = frames::ayanamsa(f.mode, f.jd_tt);
        CHECK(a.has_value());
        if (!a)
            continue;
        const double d = std::fabs(a->true_deg - f.deg) * 3600.0;
        worst_ayan = std::max(worst_ayan, d);
        if (f.jd_tt < 2420000.0)
            worst_ayan_1800 = std::max(worst_ayan_1800, d);
    }
    std::printf("  ayanamsha vs -ay<mode>: %.4f\" overall, %.4f\" since 1900\n", worst_ayan,
                worst_ayan_1800);
    CHECK(worst_ayan < 0.15);
    CHECK(worst_ayan_1800 < 0.04);

    // Sidereal apparent positions (the traditional realization:
    // tropical true-of-date longitude minus the true ayanamsha).
    double worst_pos = 0.0, worst_moon = 0.0;
    for (const SiderealFixture& f : kSiderealFixtures) {
        CalcOptions o = CalcOptions::apparent();
        o.sidereal = f.mode == 0 ? SiderealMode::FaganBradley : SiderealMode::Lahiri;
        o.speed = false;
        auto r = e.calc(f.body, f.jd_tt, o);
        CHECK(r.ok());
        if (!r)
            continue;
        const double sep = sep_as(r.value().pos.lon_deg, r.value().pos.lat_deg, f.lon, f.lat);
        if (f.body == body::kMoon)
            worst_moon = std::max(worst_moon, sep);
        else
            worst_pos = std::max(worst_pos, sep);
    }
    std::printf("  sidereal positions vs -sid<mode>: Sun/planets %.4f\", Moon %.4f\"\n", worst_pos,
                worst_moon);
    // The ayanamsha model difference plus the apparent-place pipeline
    // (<= 0.005", above).
    CHECK(worst_pos < 0.2);
    CHECK(worst_moon < 0.2);
}

TEST_CASE("de440_binary_and_spk_agree_through_engine") {
    if (!available(kDe440Path, "PROMETHEIA_DE440") || !available(kDe440sPath, "PROMETHEIA_DE440S"))
        return;
    auto a = Engine::open(kDe440Path);
    auto b = Engine::open(kDe440sPath);
    CHECK(a.ok());
    CHECK(b.ok());
    if (!a || !b)
        return;
    Engine ea = std::move(a).value();
    Engine eb = std::move(b).value();
    CHECK(eb.source().find("SPK") != std::string_view::npos);
    const int ids[] = {10, 301, 199, 299, 4, 5, 6, 7, 8, 9};
    double worst = 0.0;
    for (double jd = 2400000.5; jd < 2500000.0; jd += 3652.5 + 0.37) {
        for (int id : ids) {
            auto ra = ea.calc(id, jd);
            auto rb = eb.calc(id, jd);
            CHECK(ra.ok());
            CHECK(rb.ok());
            if (!ra || !rb)
                continue;
            const Position& p = ra.value().pos;
            const Position& q = rb.value().pos;
            worst = std::max(worst, sep_as(p.lon_deg, p.lat_deg, q.lon_deg, q.lat_deg));
        }
    }
    std::printf("  DE440 binary vs de440s.bsp through the engine: %.1e\"\n", worst);
    // The containers agree to ~4 cm (docs/SPK.md): 2e-5" at the Moon.
    CHECK(worst < 5e-5);
}

} // namespace
