#!/usr/bin/env python3
"""Checks the vendored protocol v4 pair against each other BY NAME.

third_party/ephproto/v4/{ephproto.h,registries.json} are a pinned pair, both
generated by Astrolog from EPHEMERIS_PLUGINS_PLAN.md Appendix A. This script
is the independent check that they still agree: every constant the header
names for a registry must appear in the JSON with the same value, every token
array must match the JSON's list element for element, and a JSON entry the
header does not know (a registry that grew, or a value changed) is reported
and fails the check -- the pin's whole point is to force a deliberate
re-vendor when the peer's side moves. Coverage can shrink as well as grow,
so a registry this checker pins that the JSON no longer carries is reported
too: otherwise it would simply drop out of the loop and the run would still
say "ok", with the count it prints derived from the same file that lost it.

Run as part of tools/gate.sh, and by hand:
    tools/check/ephproto4_registries.py
Exit 0 = agree, 1 = disagreement.
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
V4 = os.path.normpath(os.path.join(HERE, "..", "..", "third_party", "ephproto", "v4"))


def header_symbols(text):
    """Every `kName = value` the header defines, evaluated."""
    syms = {}

    def val(expr):
        expr = expr.strip().rstrip(",")
        m = re.fullmatch(r"(0[xX][0-9a-fA-F]+|\d+)[uUlL]*", expr)
        if m:
            return int(m.group(1), 0)
        m = re.fullmatch(r"1u?l?l?\s*<<\s*(\d+)", expr)
        if m:
            return 1 << int(m.group(1))
        if expr == "INT32_MIN":
            return -(1 << 31)
        m = re.fullmatch(r"\(?uint8_t\)?\s*\(?(\d+)\)?", expr)
        if m:
            return int(m.group(1))
        # A plain earlier symbol, possibly negated or cast.
        m = re.fullmatch(r"-?\(?(?:uint8_t|uint16_t|uint32_t|int32_t)?\s*([kA-Za-z0-9_]+)\)?", expr)
        if m and m.group(1) in syms:
            v = syms[m.group(1)]
            return -v if expr.startswith("-") else v
        return None

    # Enum bodies: `enum X ... { kA = 1, kB = 2, ... };` (assignments only).
    for m in re.finditer(r"\bk([A-Za-z0-9]+)\s*=\s*([^,;}]+)", text):
        v = val(m.group(2))
        if v is not None:
            syms["k" + m.group(1)] = v
    # `inline constexpr ... kName = expr;` and `, kName = expr,` lists.
    for m in re.finditer(r"\bk([A-Za-z0-9]+)\s*=\s*([^,;]+)[,;]", text):
        v = val(m.group(2))
        if v is not None and v < (1 << 48):
            syms.setdefault("k" + m.group(1), v)
    return syms


def header_tokens(text, array):
    m = re.search(re.escape(array) + r"\[\]\s*=\s*\{(.*?)\};", text, re.S)
    return re.findall(r'"([^"]*)"', m.group(1)) if m else None


def main():
    with open(os.path.join(V4, "ephproto.h")) as f:
        text = f.read()
    with open(os.path.join(V4, "registries.json")) as f:
        reg = json.load(f)["registries"]
    syms = header_symbols(text)

    # registry -> list of (header symbol, JSON name). None as a name: the
    # value only (for registries whose header spells no names).
    value_map = {
        "caps_bits": [("kCapF32", "f32"), ("kCapZstd", "zstd"), ("kCapCancel", "cancel"),
                      ("kCapLookup", "lookup"), ("kCapInstantLists", "instant lists"),
                      ("kCapPriority", "priority"), ("kCapSegments", "segments"),
                      ("kCapDesignations", "designations (kind 5)"),
                      ("kCapDeltaTTable", None), ("kCapDeepSky", None)],
        "correction_bits": [("kCorrLightTime", "light time"),
                            ("kCorrDeflection", "gravitational deflection"),
                            ("kCorrAberration", "aberration")],
        "element_centres": "kCentreMax",  # the header spells only the largest value
        "element_equinoxes": [("kEqJ2000", "J2000"), ("kEqB1950", "B1950"),
                              ("kEqJ1900", "J1900"), ("kEqOfDate", "of date"),
                              ("kEqExplicit", "explicit JD (equinoxJd)")],
        "error_codes": [("kErrMalformed", "malformed or non-canonical"),
                        ("kErrLimits", "over a WELCOME limit"),
                        ("kErrUnknownType", "unknown message type"), ("kErrInternal", "internal"),
                        ("kErrSource", "source, data or pin unavailable"),
                        ("kErrRateLimited", "rate limited"),
                        ("kErrToken", "token required or unknown"), ("kErrVersion", "version"),
                        ("kErrBusy", "busy (too many unread answers)"),
                        ("kErrCancelled", "cancelled"),
                        ("kErrUnsupported",
                         "unsupported (a value, capability or critical extension not advertised)"),
                        ("kErrDraining", "draining (retry elsewhere)")],
        "extra_column_bits": [("kColSigma", "σ, arcsec"), ("kColAyanamsa", "ayanamsa applied, deg"),
                              ("kColLightTime", "light time, days"), ("kColDeltaT", "ΔT used, s")],
        "forms": [("kFormSpherical", "spherical"), ("kFormRectangular", "rectangular")],
        "frames": [("kFrameTrueOfDate", "true of date"), ("kFrameMeanOfDate", "mean of date"),
                   ("kFrameJ2000", "J2000 (mean)"), ("kFrameIcrf", "ICRF")],
        "message_types": [("kMsgHello", "HELLO"), ("kMsgWelcome", "WELCOME"),
                          ("kMsgRequest", "REQUEST"), ("kMsgData", "DATA"), ("kMsgError", "ERROR"),
                          ("kMsgPing", "PING"), ("kMsgPong", "PONG"), ("kMsgCancel", "CANCEL"),
                          ("kMsgLookup", "LOOKUP"), ("kMsgLookupResult", "LOOKUP_RESULT"),
                          ("kMsgSegData", "SEGDATA")],
        "meta_flags": [("kMetaApproximated", None), ("kMetaExtrapolated", None),
                       ("kMetaHasSigma", None), ("kMetaPartial", None),
                       ("kMetaNoSpeeds", None), ("kMetaNoDistance", None),
                       ("kMetaRatesApprox", None)],
        "object_error_codes": [("kOErrNone", "none"), ("kOErrUnknownBody", "unknown body or name"),
                               ("kOErrUnsupported", None), ("kOErrCoverage", None),
                               ("kOErrDataMissing", None), ("kOErrUndefinedPoint", None),
                               ("kOErrAmbiguous", "ambiguous name"),
                               ("kOErrNumerical", None), ("kOErrInternal", "internal")],
        "object_kinds": [("kObjBody", "body"), ("kObjOrbitPoint", "orbit point"),
                         ("kObjStar", "fixed star"), ("kObjHypothetical", "named hypothetical"),
                         ("kObjElements", "elements"), ("kObjDesignation", "designation")],
        "observers": [("kObsGeo", "geocentric"), ("kObsTopo", "topocentric"),
                      ("kObsHelio", "heliocentric"),
                      ("kObsBary", "solar-system barycentre"), ("kObsBody", "body")],
        "orbit_methods": [("kMethMean", "mean"), ("kMethOsculating", "osculating"),
                          ("kMethInterpolated", None), ("kMethOscuBary", "osculating, barycentric"),
                          ("kMethFocal", "focal point")],
        "orbit_points": [("kPtAscNode", "ascending node"), ("kPtDescNode", "descending node"),
                         ("kPtPeri", "perihelion (perigee)"), ("kPtApo", "aphelion (apogee)")],
        "planes": [("kPlaneEcliptic", "ecliptic"), ("kPlaneEquator", "equator")],
        "sidereal_planes": [("kSidPlaneDate", "ecliptic of date"),
                            ("kSidPlaneAnchor", "ecliptic of the anchor epoch"),
                            ("kSidPlaneInvariable", "invariable plane of the solar system")],
        "time_scales": [("kTimeUT1", "UT1"), ("kTimeTT", "TT"), ("kTimeTDB", "TDB")],
    }
    tlv_map = {
        "request_tlvs": ["kReqTagPrecession", "kReqTagEphemerisPin", "kReqTagCatalogPin",
                         "kReqTagDatasetPin", "kReqTagDeltaTTable"],
        "welcome_capability_tlvs": ["kCapTagKinds", "kCapTagObservers",
                                    "kCapTagPlanesFormsFrames", "kCapTagCorrections",
                                    "kCapTagOrbit", "kCapTagColumns", "kCapTagZodiacs",
                                    "kCapTagSiderealPlanes", "kCapTagTimeScales",
                                    "kCapTagCoverage", "kCapTagCatalogs", "kCapTagDeltaT",
                                    "kCapTagPrecession", "kCapTagRate", "kCapTagSegments",
                                    "kCapTagLookup", "kCapTagHypotheticals", "kCapTagEquinoxes",
                                    "kCapTagRatesBound", "kCapTagCorrectionsByKind"],
    }
    token_map = {"zodiac_tokens": "kZodiacTokens", "hypothetical_tokens": "kHypotheticalTokens"}
    # Reserved by design: the registry holds the value, the header implements
    # nothing for it (an unknown type is kUnsupported at the session).
    reserved = {"message_types": {11, 12, 13, 14}}
    # No header constants: the registry's token strings are the payload of
    # REQUEST TLV 0x0003 and this check pins only the tag (in tlv_map).
    unchecked = {"precession_model_tokens"}

    bad = []
    # The tables above name every registry this checker knows. A registry the
    # JSON no longer carries would otherwise vanish from the loop below and
    # the run would still say "ok" -- the pin's coverage shrinking silently,
    # which is the one direction "unknown to this checker" cannot catch.
    pinned = set(value_map) | set(tlv_map) | set(token_map) | set(unchecked)
    gone = sorted(pinned - set(reg))
    for name in gone:
        bad.append(f"{name}: this checker pins it and the vendored registries.json no longer "
                   f"carries it -- the pair changed shape, re-vendor deliberately")
    n_checked = 0
    for name, r in reg.items():
        if name in unchecked:
            continue
        n_checked += 1
        entries = r["entries"]
        if name in token_map:
            array = token_map[name]
            want = header_tokens(text, array)
            got = [e["token"] for e in entries]
            if want != got:
                bad.append(f"{name}: header {array} differs from the registry "
                           f"({len(want or [])} vs {len(got)} tokens)"
                           + ("" if want == got else
                              "; first diff: " + next((f"{a!r} != {b!r}" for a, b in zip(want, got)
                                                       if a != b), "length")))
            continue
        if name in value_map:
            spec = value_map[name]
            if isinstance(spec, str):
                # A registry whose header spells only the largest value.
                want = max(x.get("value", x.get("mask")) for x in entries)
                if syms.get(spec) != want:
                    bad.append(f"{name}: largest value {want} in the registry, "
                               f"header {spec} = {syms.get(spec)}")
                continue
            covered = set()
            for sym, jname in spec:
                if sym not in syms:
                    bad.append(f"{name}: header symbol {sym} not found")
                    continue
                if jname is not None:
                    e = [x for x in entries if x["name"] == jname]
                else:
                    # No name known: match the registry entry by the symbol's value.
                    e = [x for x in entries
                         if x.get("value", x.get("mask")) == syms[sym]]
                if not e:
                    bad.append(f"{name}: no entry for {jname or sym} "
                               f"(header value {syms[sym]})")
                    continue
                v = e[0].get("value", e[0].get("mask"))
                if v != syms[sym]:
                    bad.append(f"{name}: {jname or sym} = {v} in the registry, "
                               f"header {sym} = {syms[sym]}")
                covered.add(v)
            # Every valued entry the header table does not cover, and is not
            # reserved by design, is the registry having grown: re-vendor.
            for x in entries:
                v = x.get("value", x.get("mask"))
                if v is None or v in covered or v in reserved.get(name, set()):
                    continue
                bad.append(f"{name}: registry entry {x['name']!r} ({v}) is not in the "
                           f"header table -- re-vendor")
            continue
        if name in tlv_map:
            for sym in tlv_map[name]:
                if sym not in syms:
                    bad.append(f"{name}: header symbol {sym} not found")
                    continue
                if not any(e["tag"] == syms[sym] for e in entries):
                    bad.append(f"{name}: no TLV with tag {hex(syms[sym])} ({sym})")
            for e in entries:
                if e["tag"] not in {syms[s] for s in tlv_map[name] if s in syms}:
                    bad.append(f"{name}: TLV tag {hex(e['tag'])} is not in the header -- re-vendor")
            continue
        bad.append(f"{name}: registry unknown to this checker -- extend the tables")

    for b in bad:
        print("DISAGREE " + b)
    if bad:
        print(f"{len(bad)} disagreement(s); the vendored pair must be re-checked and re-pinned")
        return 1
    print(f"registries ok: {n_checked} of {len(reg)} registries checked, {len(syms)} header symbols, by name and value")
    return 0


if __name__ == "__main__":
    sys.exit(main())
