// SPDX-License-Identifier: GPL-2.0-or-later
//
// Frame transformations: IAU 2006 precession, full IAU 2000A nutation,
// obliquity, sidereal time, and a topocentric helper.
//
// All source constants are from USNO Circular 179 (Kaplan 2005, public
// domain); the 1365-term nutation series is the circular's printed
// MHB2000 table, regenerated by tools/gen/gen_nutation_table.py.
// Derivation, conventions and accuracy notes: docs/FRAMES.md.
//
// Conventions: vectors are ICRF rectangular (equatorial J2000 axes);
// matrices are row-major 3x3, applied as r_out = M * r_in; the matrix
// builders take the TT (or TDB, indistinguishable at the 10 us level)
// Julian date and compute T = centuries from J2000 internally.
//
// "Ecliptic of date" is the mean ecliptic plane of date with the true
// equinox as longitude origin: nutation shifts longitudes by dpsi and
// leaves latitudes unchanged, matching the classical statement and the
// Swiss Ephemeris convention (verified differentially to 0.0005",
// docs/FRAMES.md).
#ifndef PROMETHEIA_FRAMES_HPP
#define PROMETHEIA_FRAMES_HPP

#include <optional>

namespace prometheia::frames {

// The 14 fundamental arguments (radians, [0, 2pi)): eight planetary mean
// longitudes, general precession, then l, l', F, D, Omega.
void fundamental_arguments(double jd_tt, double phi[14]);

// Full IAU 2000A nutation: dpsi (longitude) and deps (obliquity),
// radians.
void nutation(double jd_tt, double& dpsi, double& deps);

// The same series with its first and second time derivatives (radians,
// radians/day, radians/day^2), evaluated analytically term by term:
// out = {dpsi, deps, dpsi', deps', dpsi'', deps''}. Lets a caller carry the
// nutation to nearby epochs by a Taylor step instead of re-summing 1365
// terms (docs/FRAMES.md).
void nutation_with_rates(double jd_tt, double out[6]);

// The same at two instants at once, each result identical to
// nutation_with_rates' (the interpolator's two nodes around a fresh instant).
void nutation_with_rates_pair(double jd_a, double jd_b, double out_a[6], double out_b[6]);

// The same series summed the way the circular prints it, one sine and one
// cosine per term. nutation() rearranges that sum to build each term's pair
// by angle addition instead, which is eight times faster; this exists so a
// test can hold the two against each other, and nothing else should call it.
void nutation_printed_form(double jd_tt, double& dpsi, double& deps);

// IAU 2000A nutation interpolated from nodes on a fixed half-day grid: each
// node holds the series value and its first and second derivatives
// (nutation_with_rates), and an epoch between two nodes takes the quintic
// Hermite polynomial matching all six. Measured against the full series
// over 1800-2100: 0.004 uas (docs/FRAMES.md). The value depends only on the
// epoch, never on query history. Nodes are kept in a direct-mapped cache
// (4096 nodes, ~200 KB, about 5.6 years), so a sweep of many bodies over
// one time window sums the series once per half day in total. Not
// thread-safe; one per thread (the Engine keeps its own).
class NutationInterpolator {
public:
    NutationInterpolator();
    ~NutationInterpolator();
    NutationInterpolator(const NutationInterpolator&) = delete;
    NutationInterpolator& operator=(const NutationInterpolator&) = delete;

    void at(double jd_tt, double& dpsi, double& deps);

    // Series sums so far (for tests and benchmarks).
    unsigned long long evaluations() const { return evaluations_; }

    static constexpr double kNodeSpacingDays = 0.5;

private:
    struct Node;
    const Node& node(long long index);
    Node* nodes_;
    unsigned long long evaluations_ = 0;
};

// IAU 2006 precession angles zeta, z, theta (radians).
void precession_angles(double jd_tt, double& zeta, double& z, double& theta);

// IAU 2006 mean obliquity of the ecliptic (radians).
double mean_obliquity(double jd_tt);

// --- Matrices, row-major 3x3, r_out = M * r_in, all from ICRF -------

// Frame bias B = R1(-eta0) R2(xi0) R3(d_alpha0): ICRF -> mean equator
// and equinox of J2000.0, with d_alpha0 = -14.6 mas, xi0 = -16.617 mas,
// eta0 = -6.8192 mas (Circular 179 ch. 5). About 23 mas; the date-frame
// matrices below do NOT include it: compose M * B for a bias-consistent
// chain (the engine does).
void frame_bias_matrix(double m[9]);

// Mean equator & equinox of date (IAU 2006 precession alone).
void mean_equator_of_date_matrix(double jd_tt, double m[9]);

// True equator & equinox of date (precession + full 2000A nutation).
void true_equator_of_date_matrix(double jd_tt, double m[9]);

// Mean ecliptic of date, mean equinox.
void mean_ecliptic_of_date_matrix(double jd_tt, double m[9]);

// Ecliptic of date (mean plane) with the true equinox as origin: the
// classical "apparent longitude" frame.
void true_ecliptic_of_date_matrix(double jd_tt, double m[9]);

// --- Long-term precession (Vondrak, Capitaine & Wallace 2011) ---------
//
// Which precession model a date frame uses. IAU 2006 is the default and
// the standard near the present; Vondrak 2011 for epochs centuries or more
// from J2000.
enum class PrecessionModel { IAU2006 = 0, Vondrak2011 = 1 };

// The model-selecting forms of the precession-dependent quantities: the
// mean equator of date matrix (no bias), mean obliquity, general
// precession in longitude, and the ayanamshas built on it.
void mean_equator_of_date_matrix(double jd_tt, PrecessionModel model, double m[9]);
double mean_obliquity(double jd_tt, PrecessionModel model);
double precession_in_longitude_deg(double jd_tt, PrecessionModel model);
//
// Series fitted to IAU 2006 near J2000 and to numerical integrations over
// +-200 millennia (A&A 534, A22, 2011; Table 1 corrected per A&A 541, C1,
// 2012): a cubic polynomial plus 8-14 periodic terms for each parameter.
// Comparable to IAU 2006 within a few centuries of J2000, a few arcseconds
// over the historical period, where the IAU 2006 polynomials degrade
// quickly. All vectors and matrices refer to the mean equator and equinox
// of J2000.0 (compose with frame_bias_matrix for ICRF input).

// Unit vector of the ecliptic pole of date (Eq. 8, Table 1).
void ltp_ecliptic_pole(double jd_tt, double k[3]);

// Unit vector of the mean equator pole of date (Eq. 9, Table 2).
void ltp_equator_pole(double jd_tt, double n[3]);

// Mean equator & equinox of date from J2000.0 mean, built from the two
// poles (Eq. 23): rows = equinox (n x k normalized), n x equinox, n.
void ltp_mean_equator_of_date_matrix(double jd_tt, double m[9]);

// Mean obliquity of date (radians): the angle between the two poles, so
// that it is exactly consistent with ltp_mean_equator_of_date_matrix.
double ltp_mean_obliquity(double jd_tt);

// General precession in longitude p_A from J2000 (degrees; Eq. 10,
// Table 3).
double ltp_precession_in_longitude_deg(double jd_tt);

// The obliquity series epsilon_A of Eq. 10 (Table 3), radians; exposed for
// validation against the pole angle.
double ltp_obliquity_series(double jd_tt);

// --- Sidereal zodiacs (ayanamshas) ----------------------------------

// A sidereal zodiac is the ecliptic of date with its longitude origin
// moved west by the ayanamsha. Published zodiacs anchor the ayanamsha
// at one epoch; away from it the value grows with the IAU 2006 general
// precession in longitude (mean), and the true ayanamsha adds the
// nutation in longitude. Both are measured on the ecliptic of date,
// the traditional realization (verified against the Swiss Ephemeris
// output to <= 0.08" over 1600-2400, docs/ENGINE.md).
struct Ayanamsa {
    double mean_deg; // precession only
    double true_deg; // mean + nutation in longitude
};

// The published zodiacs by their conventional numbering (the Swiss
// Ephemeris command-line -ay<mode>): 0 Fagan/Bradley, 1 Lahiri.
// nullopt for any other mode.
std::optional<Ayanamsa> ayanamsa(int mode, double jd_tt);

// A user-anchored zodiac: the MEAN ayanamsha is ayan0_mean_deg at the
// TT epoch t0_jtdb (the same convention as the Swiss Ephemeris
// -sidudef anchor).
Ayanamsa ayanamsa_anchored(double t0_jtdb, double ayan0_mean_deg, double jd_tt);

// A published zodiac's zero point: the TT epoch of its definition and the
// MEAN ayanamsha there. nullopt for any other mode.
struct AyanamsaAnchor {
    double t0_jtdb;
    double mean0_deg;
};
std::optional<AyanamsaAnchor> ayanamsa_anchor(int mode);

// The invariable plane of the solar system: the unit normal to the total
// angular momentum of the Sun, the planetary-system barycentres and Pluto,
// in ICRF, from JPL DE440's states and GM constants at J2000.0. Computed by
// tests/test_frames.cpp's invariable_plane_from_de440 (which recomputes it
// when the DE440 file is present); constant across 1800-2200 to 1e-9, i.e.
// the mass set conserves it. On the J2000 ecliptic: inclination 1.578700
// deg, ascending node 107.582322 deg.
inline constexpr double kInvariablePoleIcrf[3] = {0.026262993692212, -0.389990518230968,
                                                  0.920444268194584};

// The same, with the general precession of the given model.
std::optional<Ayanamsa> ayanamsa(int mode, double jd_tt, PrecessionModel model);
Ayanamsa ayanamsa_anchored(double t0_jtdb, double ayan0_mean_deg, double jd_tt,
                           PrecessionModel model);

// IAU 2006 general precession in longitude from J2000 (degrees): the
// motion of the mean equinox along the ecliptic of date.
double precession_in_longitude_deg(double jd_tt);

// --- Sidereal time --------------------------------------------------

// Earth Rotation Angle (radians, [0, 2pi)), a function of UT1 alone.
double earth_rotation_angle(double jd_ut1);

// Greenwich mean / apparent sidereal time (radians). Both need UT1 for
// the Earth Rotation Angle and TT for the equinox-precession terms;
// gmst_rad(jd_ut1, jd_tt), gast adds the equation of the equinoxes.
double gmst_rad(double jd_ut1, double jd_tt);
double equation_of_equinoxes_rad(double jd_tt);
double gast_rad(double jd_ut1, double jd_tt);
// The same with the nutation in longitude and mean obliquity of date already
// in hand (the series is the expensive part), bit-identical to the above.
double equation_of_equinoxes_rad(double jd_tt, double dpsi, double eps_mean);
double gast_rad(double jd_ut1, double jd_tt, double dpsi, double eps_mean);

// UT1 (JD) at which the local apparent sidereal time at east longitude
// site_lon_rad is last_rad under this library's GAST, starting from a
// guess within a few minutes (Newton on the sidereal rate). This recovers
// an outside source's Earth rotation from its published sidereal time, so
// a comparison uses one rotation rather than two Delta T models.
double ut1_from_sidereal_time(double jd_ut1_guess, double jd_tt, double last_rad,
                              double site_lon_rad);

// --- Topocentric helper ---------------------------------------------

struct GeoSite {
    double lon_rad = 0.0;  // geodetic longitude, east positive
    double lat_rad = 0.0;  // geodetic latitude
    double height_m = 0.0; // above the WGS84 ellipsoid
};

// Geocentric position of the site (km) in the true equator and equinox
// of date frame: rotate by the given apparent sidereal time. Polar
// motion (<= 0.3") is neglected.
void observer_geocentric(const GeoSite& site, double gast, double out[3]);

} // namespace prometheia::frames

#endif // PROMETHEIA_FRAMES_HPP